In [1]:
import shutil
import os
import pandas as pd
import numpy as np
import glob
from pathlib import Path

In [19]:
base = '..\\Pediatric_Anxiety_Disorder'
source_dir = os.path.join(base,'sub-24015')
source_dir

'..\\Pediatric_Anxiety_Disorder\\sub-24015'

In [15]:
names = pd.read_csv('names.txt', delimiter='\\s+', header=None)[0].values.tolist()
print(names)

['sub-24017', 'sub-24021', 'sub-24022', 'sub-24029', 'sub-24033', 'sub-24038', 'sub-24039', 'sub-24040', 'sub-24046', 'sub-24050', 'sub-24067', 'sub-24073', 'sub-24089', 'sub-24091', 'sub-24106', 'sub-24115', 'sub-24118', 'sub-24127', 'sub-24139', 'sub-24142', 'sub-24145', 'sub-24146', 'sub-24148', 'sub-24151', 'sub-24182', 'sub-24197', 'sub-24198', 'sub-24212', 'sub-24217', 'sub-24236', 'sub-24240', 'sub-24260', 'sub-24270', 'sub-24275', 'sub-24276', 'sub-24300', 'sub-24353']

In [16]:
len(names)

37

In [17]:
n = len(names)
for i in range(n):
    destination_dir = os.path.join(base, names[i])
    shutil.copytree(source_dir, destination_dir)
    print(f"Created {destination_dir}")

Created ..\Pediatric_Anxiety_Disorder\sub-24017
Created ..\Pediatric_Anxiety_Disorder\sub-24021
Created ..\Pediatric_Anxiety_Disorder\sub-24022
Created ..\Pediatric_Anxiety_Disorder\sub-24029
Created ..\Pediatric_Anxiety_Disorder\sub-24033
Created ..\Pediatric_Anxiety_Disorder\sub-24038
Created ..\Pediatric_Anxiety_Disorder\sub-24039
Created ..\Pediatric_Anxiety_Disorder\sub-24040
Created ..\Pediatric_Anxiety_Disorder\sub-24046
Created ..\Pediatric_Anxiety_Disorder\sub-24050
Created ..\Pediatric_Anxiety_Disorder\sub-24067
Created ..\Pediatric_Anxiety_Disorder\sub-24073
Created ..\Pediatric_Anxiety_Disorder\sub-24089
Created ..\Pediatric_Anxiety_Disorder\sub-24091
Created ..\Pediatric_Anxiety_Disorder\sub-24106
Created ..\Pediatric_Anxiety_Disorder\sub-24115
Created ..\Pediatric_Anxiety_Disorder\sub-24118
Created ..\Pediatric_Anxiety_Disorder\sub-24127
Created ..\Pediatric_Anxiety_Disorder\sub-24139
Created ..\Pediatric_Anxiety_Disorder\sub-24142
Created ..\Pediatric_Anxiety_Disorder\sub-24145
Created ..\Pediatric_Anxiety_Disorder\sub-24146
Created ..\Pediatric_Anxiety_Disorder\sub-24148
Created ..\Pediatric_Anxiety_Disorder\sub-24151
Created ..\Pediatric_Anxiety_Disorder\sub-24182
Created ..\Pediatric_Anxiety_Disorder\sub-24197
Created ..\Pediatric_Anxiety_Disorder\sub-24198
Created ..\Pediatric_Anxiety_Disorder\sub-24212
Created ..\Pediatric_Anxiety_Disorder\sub-24217
Created ..\Pediatric_Anxiety_Disorder\sub-24236
Created ..\Pediatric_Anxiety_Disorder\sub-24240
Created ..\Pediatric_Anxiety_Disorder\sub-24260
Created ..\Pediatric_Anxiety_Disorder\sub-24270
Created ..\Pediatric_Anxiety_Disorder\sub-24275
Created ..\Pediatric_Anxiety_Disorder\sub-24276
Created ..\Pediatric_Anxiety_Disorder\sub-24300
Created ..\Pediatric_Anxiety_Disorder\sub-24353

In [48]:
downloads = "C:\\Users\\aleen\\Downloads\\"
files = glob.glob(os.path.join(downloads, "sub*.gz"))
files

['C:\\Users\\aleen\\Downloads\\sub-24038_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-2_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-2_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-2_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-2_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-2_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-2_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-2_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-2_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-2_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-2_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-2_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-2_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-2_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-2_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-2_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-2_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-2_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-2_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24046_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24046_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24046_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24046_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24046_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24046_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-2_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-2_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-2_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-2_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-2_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-2_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-2_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-2_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-2_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-2_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-2_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-2_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24073_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24073_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24073_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24073_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24073_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24073_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-2_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-2_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-2_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-2_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-2_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-2_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-2_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-2_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-2_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-2_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-2_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-2_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24106_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24106_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24106_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24106_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24106_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24106_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24115_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24115_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24115_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24115_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24115_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24115_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24118_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24118_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24118_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24118_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24118_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24118_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24127_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24127_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24127_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24127_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24127_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24127_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-2_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-2_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-2_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-2_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-2_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-2_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24142_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24142_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24142_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24142_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24142_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24142_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24145_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24145_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24145_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24145_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24145_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24145_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-2_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-2_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-2_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-2_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-2_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-2_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24148_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24148_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24148_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24148_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24148_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24148_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-2_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-2_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-2_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-2_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-2_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-2_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24182_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24182_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24182_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24182_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24182_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24182_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24197_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24197_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24197_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24197_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24197_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24197_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24198_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24198_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24198_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24198_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24198_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24198_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24212_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24212_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24212_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24212_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24212_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24212_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24217_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24217_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24217_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24217_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24217_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24217_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24236_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24236_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24236_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24236_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24236_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24236_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-2_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-2_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-2_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-2_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-2_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-2_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24260_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24260_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24260_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24260_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24260_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24260_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24270_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24270_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24270_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24270_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24270_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24270_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24275_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24275_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24275_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24275_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24275_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24275_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24276_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24276_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24276_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24276_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24276_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24276_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-1_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-2_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-2_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-2_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-2_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-2_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-2_task-TAU2_run-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24353_ses-1_T1w.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24353_ses-1_task-rest_echo-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24353_ses-1_task-rest_echo-2_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24353_ses-1_task-rest_echo-3_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24353_ses-1_task-TAU2_run-1_bold.nii.gz',
 'C:\\Users\\aleen\\Downloads\\sub-24353_ses-1_task-TAU2_run-2_bold.nii.gz']

In [49]:
len(files)

264

In [50]:
for f in files:
    fname = os.path.basename(f)
    parts = fname.split("_")

    print(parts)

    subject = parts[0]
    session = None
    modality = None

    for p in parts:
        if p.startswith('ses-'):
            session = p
        if p.endswith('.nii.gz'):
            modality = p.replace('.nii.gz', '')

    if modality=='T1w':
        dtype = 'anat'
    elif modality=='bold':
        dtype = 'func'
    else:
        dtype = 'misc'

    dest_dir = os.path.join(base, subject)
    if session:
        dest_dir = os.path.join(dest_dir, session)
    if dtype!='misc':
        dest_dir = os.path.join(dest_dir, dtype)
        os.makedirs(dest_dir, exist_ok=True)
        dest_file = os.path.join(dest_dir, fname)
        shutil.move(f, dest_file)
        print(f"Moved {fname} to {dest_dir}")

['sub-24038', 'ses-1', 'T1w.nii.gz']
Moved sub-24038_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\anat
['sub-24038', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24038_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\func
['sub-24038', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24038_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\func
['sub-24038', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24038_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\func
['sub-24038', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24038_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\func
['sub-24038', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24038_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\func
['sub-24038', 'ses-2', 'T1w.nii.gz']
Moved sub-24038_ses-2_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-2\anat
['sub-24038', 'ses-2', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24038_ses-2_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-2\func
['sub-24038', 'ses-2', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24038_ses-2_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-2\func
['sub-24038', 'ses-2', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24038_ses-2_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-2\func
['sub-24038', 'ses-2', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24038_ses-2_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-2\func
['sub-24038', 'ses-2', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24038_ses-2_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-2\func
['sub-24039', 'ses-1', 'T1w.nii.gz']
Moved sub-24039_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\anat
['sub-24039', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24039_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\func
['sub-24039', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24039_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\func
['sub-24039', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24039_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\func
['sub-24039', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24039_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\func
['sub-24039', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24039_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\func
['sub-24039', 'ses-2', 'T1w.nii.gz']
Moved sub-24039_ses-2_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-2\anat
['sub-24039', 'ses-2', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24039_ses-2_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-2\func
['sub-24039', 'ses-2', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24039_ses-2_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-2\func
['sub-24039', 'ses-2', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24039_ses-2_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-2\func
['sub-24039', 'ses-2', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24039_ses-2_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-2\func
['sub-24039', 'ses-2', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24039_ses-2_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-2\func
['sub-24040', 'ses-1', 'T1w.nii.gz']
Moved sub-24040_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\anat
['sub-24040', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24040_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\func
['sub-24040', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24040_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\func
['sub-24040', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24040_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\func
['sub-24040', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24040_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\func
['sub-24040', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24040_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\func
['sub-24040', 'ses-2', 'T1w.nii.gz']
Moved sub-24040_ses-2_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-2\anat
['sub-24040', 'ses-2', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24040_ses-2_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-2\func
['sub-24040', 'ses-2', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24040_ses-2_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-2\func
['sub-24040', 'ses-2', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24040_ses-2_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-2\func
['sub-24040', 'ses-2', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24040_ses-2_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-2\func
['sub-24040', 'ses-2', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24040_ses-2_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-2\func
['sub-24046', 'ses-1', 'T1w.nii.gz']
Moved sub-24046_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\anat
['sub-24046', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24046_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\func
['sub-24046', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24046_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\func
['sub-24046', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24046_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\func
['sub-24046', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24046_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\func
['sub-24046', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24046_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\func
['sub-24050', 'ses-1', 'T1w.nii.gz']
Moved sub-24050_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\anat
['sub-24050', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24050_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\func
['sub-24050', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24050_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\func
['sub-24050', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24050_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\func
['sub-24050', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24050_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\func
['sub-24050', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24050_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\func
['sub-24050', 'ses-2', 'T1w.nii.gz']
Moved sub-24050_ses-2_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-2\anat
['sub-24050', 'ses-2', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24050_ses-2_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-2\func
['sub-24050', 'ses-2', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24050_ses-2_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-2\func
['sub-24050', 'ses-2', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24050_ses-2_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-2\func
['sub-24050', 'ses-2', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24050_ses-2_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-2\func
['sub-24050', 'ses-2', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24050_ses-2_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-2\func
['sub-24067', 'ses-1', 'T1w.nii.gz']
Moved sub-24067_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-1\anat
['sub-24067', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24067_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-1\func
['sub-24067', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24067_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-1\func
['sub-24067', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24067_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-1\func
['sub-24067', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24067_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-1\func
['sub-24067', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24067_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-1\func
['sub-24067', 'ses-2', 'T1w.nii.gz']
Moved sub-24067_ses-2_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-2\anat
['sub-24067', 'ses-2', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24067_ses-2_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-2\func
['sub-24067', 'ses-2', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24067_ses-2_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-2\func
['sub-24067', 'ses-2', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24067_ses-2_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-2\func
['sub-24067', 'ses-2', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24067_ses-2_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-2\func
['sub-24067', 'ses-2', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24067_ses-2_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-2\func
['sub-24073', 'ses-1', 'T1w.nii.gz']
Moved sub-24073_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24073\ses-1\anat
['sub-24073', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24073_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24073\ses-1\func
['sub-24073', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24073_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24073\ses-1\func
['sub-24073', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24073_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24073\ses-1\func
['sub-24073', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24073_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24073\ses-1\func
['sub-24073', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24073_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24073\ses-1\func
['sub-24089', 'ses-1', 'T1w.nii.gz']
Moved sub-24089_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24089\ses-1\anat
['sub-24089', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24089_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24089\ses-1\func
['sub-24089', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24089_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24089\ses-1\func
['sub-24089', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24089_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24089\ses-1\func
['sub-24089', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24089_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24089\ses-1\func
['sub-24089', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24089_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24089\ses-1\func
['sub-24089', 'ses-2', 'T1w.nii.gz']
Moved sub-24089_ses-2_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24089\ses-2\anat
['sub-24089', 'ses-2', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24089_ses-2_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24089\ses-2\func
['sub-24089', 'ses-2', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24089_ses-2_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24089\ses-2\func
['sub-24089', 'ses-2', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24089_ses-2_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24089\ses-2\func
['sub-24089', 'ses-2', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24089_ses-2_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24089\ses-2\func
['sub-24089', 'ses-2', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24089_ses-2_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24089\ses-2\func
['sub-24091', 'ses-1', 'T1w.nii.gz']
Moved sub-24091_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24091\ses-1\anat
['sub-24091', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24091_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24091\ses-1\func
['sub-24091', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24091_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24091\ses-1\func
['sub-24091', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24091_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24091\ses-1\func
['sub-24091', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24091_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24091\ses-1\func
['sub-24091', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24091_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24091\ses-1\func
['sub-24091', 'ses-2', 'T1w.nii.gz']
Moved sub-24091_ses-2_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24091\ses-2\anat
['sub-24091', 'ses-2', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24091_ses-2_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24091\ses-2\func
['sub-24091', 'ses-2', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24091_ses-2_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24091\ses-2\func
['sub-24091', 'ses-2', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24091_ses-2_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24091\ses-2\func
['sub-24091', 'ses-2', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24091_ses-2_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24091\ses-2\func
['sub-24091', 'ses-2', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24091_ses-2_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24091\ses-2\func
['sub-24106', 'ses-1', 'T1w.nii.gz']
Moved sub-24106_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24106\ses-1\anat
['sub-24106', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24106_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24106\ses-1\func
['sub-24106', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24106_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24106\ses-1\func
['sub-24106', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24106_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24106\ses-1\func
['sub-24106', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24106_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24106\ses-1\func
['sub-24106', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24106_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24106\ses-1\func
['sub-24115', 'ses-1', 'T1w.nii.gz']
Moved sub-24115_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24115\ses-1\anat
['sub-24115', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24115_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24115\ses-1\func
['sub-24115', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24115_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24115\ses-1\func
['sub-24115', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24115_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24115\ses-1\func
['sub-24115', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24115_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24115\ses-1\func
['sub-24115', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24115_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24115\ses-1\func
['sub-24118', 'ses-1', 'T1w.nii.gz']
Moved sub-24118_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24118\ses-1\anat
['sub-24118', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24118_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24118\ses-1\func
['sub-24118', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24118_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24118\ses-1\func
['sub-24118', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24118_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24118\ses-1\func
['sub-24118', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24118_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24118\ses-1\func
['sub-24118', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24118_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24118\ses-1\func
['sub-24127', 'ses-1', 'T1w.nii.gz']
Moved sub-24127_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24127\ses-1\anat
['sub-24127', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24127_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24127\ses-1\func
['sub-24127', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24127_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24127\ses-1\func
['sub-24127', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24127_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24127\ses-1\func
['sub-24127', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24127_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24127\ses-1\func
['sub-24127', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24127_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24127\ses-1\func
['sub-24139', 'ses-1', 'T1w.nii.gz']
Moved sub-24139_ses-1_T1w.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24139\ses-1\anat
['sub-24139', 'ses-1', 'task-rest', 'echo-1', 'bold.nii.gz']
Moved sub-24139_ses-1_task-rest_echo-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24139\ses-1\func
['sub-24139', 'ses-1', 'task-rest', 'echo-2', 'bold.nii.gz']
Moved sub-24139_ses-1_task-rest_echo-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24139\ses-1\func
['sub-24139', 'ses-1', 'task-rest', 'echo-3', 'bold.nii.gz']
Moved sub-24139_ses-1_task-rest_echo-3_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24139\ses-1\func
['sub-24139', 'ses-1', 'task-TAU2', 'run-1', 'bold.nii.gz']
Moved sub-24139_ses-1_task-TAU2_run-1_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24139\ses-1\func
['sub-24139', 'ses-1', 'task-TAU2', 'run-2', 'bold.nii.gz']
Moved sub-24139_ses-1_task-TAU2_run-2_bold.nii.gz to ..\Pediatric_Anxiety_Disorder\sub-24139\ses-1\func
['sub-24139', 'ses-2', 'T1w.nii.gz']

In [53]:
path = r"C:\Users\aleen\Downloads\sub-24017_ses-1_task-TAU2_run-2_events.txt"
pd.read_csv(path, delimiter='\\s+')

       onset  duration   trial_type  response_time
0      9.730       0.5  incongruent          0.403
1     12.087       0.5  incongruent          0.368
2     14.695       0.5    congruent          0.467
3     17.403       0.5      neutral          0.470
4     24.808       0.5  incongruent          0.431
..       ...       ...          ...            ...
115  394.081       0.5    congruent          0.567
116  396.689       0.5    congruent          0.585
117  399.046       0.5      neutral          0.517
118  403.961       0.5      neutral          0.540
119  409.177       0.5      neutral          0.639

[120 rows x 4 columns]

In [56]:
downloads = "C:\\Users\\aleen\\Downloads\\"
files = glob.glob(os.path.join(downloads, "sub*.txt"))
files

['C:\\Users\\aleen\\Downloads\\sub-24017_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24017_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24017_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24021_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24021_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24021_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24021_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24022_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24022_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24022_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24022_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24029_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24029_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24029_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24029_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24033_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24033_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24046_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24046_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24073_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24073_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24106_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24106_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24115_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24115_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24118_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24118_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24127_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24127_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24142_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24142_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24145_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24145_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24148_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24148_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24182_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24182_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24197_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24197_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24198_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24198_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24212_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24212_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24217_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24217_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24236_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24236_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24260_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24260_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24270_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24270_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24275_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24275_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24276_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24276_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-1_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-2_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-2_task-TAU2_run-2_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24353_ses-1_task-TAU2_run-1_events.txt',
 'C:\\Users\\aleen\\Downloads\\sub-24353_ses-1_task-TAU2_run-2_events.txt']

In [68]:
len(files)

105

In [65]:
for file in files:
    newfile = os.path.basename(file).split('.')[0]+'.tsv'
    pd.read_csv(file, delimiter='\\s+').to_csv(os.path.join(os.path.dirname(file), newfile), sep='\t', index=False)

In [69]:
downloads = "C:\\Users\\aleen\\Downloads\\"
files = glob.glob(os.path.join(downloads, "sub*.tsv"))
files

['C:\\Users\\aleen\\Downloads\\sub-24004_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24004_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24004_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24004_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24015_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24015_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24017_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24017_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24017_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24017_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24021_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24021_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24021_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24021_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24022_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24022_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24022_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24022_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24029_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24029_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24029_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24029_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24033_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24033_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24038_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24039_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24040_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24046_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24046_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24050_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24067_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24073_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24073_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24089_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24091_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24106_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24106_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24115_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24115_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24118_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24118_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24127_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24127_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24139_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24142_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24142_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24145_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24145_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24146_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24148_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24148_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24151_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24182_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24182_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24197_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24197_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24198_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24198_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24212_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24212_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24217_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24217_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24236_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24236_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24240_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24260_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24260_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24270_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24270_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24275_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24275_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24276_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24276_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-1_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-2_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24300_ses-2_task-TAU2_run-2_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24353_ses-1_task-TAU2_run-1_events.tsv',
 'C:\\Users\\aleen\\Downloads\\sub-24353_ses-1_task-TAU2_run-2_events.tsv']

In [70]:
len(files)

112

In [72]:
tsv_files = glob.glob(os.path.join(downloads, "sub*.tsv"))
json_files = glob.glob(os.path.join(downloads, "sub*.json"))
files = tsv_files + json_files
print(len(tsv_files), len(json_files), len(files))

0 336 336

In [73]:
for f in files:
    fname = os.path.basename(f)
    parts = fname.split("_")

    print(parts)

    subject = parts[0]
    session = None
    modality = None

    for p in parts:
        if p.startswith('ses-'):
            session = p
        if p.endswith('.json'):
            modality = p.replace('.json', '')
        elif p.endswith('.tsv'):
            modality = p.replace('.tsv', '')

    if modality=='T1w':
        dtype = 'anat'
    elif modality=='bold' or modality=='events':
        dtype = 'func'
    else:
        dtype = 'misc'

    dest_dir = os.path.join(base, subject)
    if session:
        dest_dir = os.path.join(dest_dir, session)
    if dtype!='misc':
        dest_dir = os.path.join(dest_dir, dtype)
        os.makedirs(dest_dir, exist_ok=True)
        dest_file = os.path.join(dest_dir, fname)
        shutil.move(f, dest_file)
        print(f"Moved {fname} to {dest_dir}")

['sub-24004', 'ses-1', 'T1w.json']
Moved sub-24004_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24004\ses-1\anat
['sub-24004', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24004_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24004\ses-1\func
['sub-24004', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24004_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24004\ses-1\func
['sub-24004', 'ses-1', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24004_ses-1_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24004\ses-1\func
['sub-24004', 'ses-1', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24004_ses-1_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24004\ses-1\func
['sub-24004', 'ses-1', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24004_ses-1_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24004\ses-1\func
['sub-24004', 'ses-2', 'T1w.json']
Moved sub-24004_ses-2_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24004\ses-2\anat
['sub-24004', 'ses-2', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24004_ses-2_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24004\ses-2\func
['sub-24004', 'ses-2', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24004_ses-2_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24004\ses-2\func
['sub-24004', 'ses-2', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24004_ses-2_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24004\ses-2\func
['sub-24004', 'ses-2', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24004_ses-2_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24004\ses-2\func
['sub-24004', 'ses-2', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24004_ses-2_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24004\ses-2\func
['sub-24015', 'ses-1', 'T1w.json']
Moved sub-24015_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24015\ses-1\anat
['sub-24015', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24015_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24015\ses-1\func
['sub-24015', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24015_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24015\ses-1\func
['sub-24015', 'ses-1', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24015_ses-1_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24015\ses-1\func
['sub-24015', 'ses-1', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24015_ses-1_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24015\ses-1\func
['sub-24015', 'ses-1', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24015_ses-1_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24015\ses-1\func
['sub-24017', 'ses-1', 'T1w.json']
Moved sub-24017_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24017\ses-1\anat
['sub-24017', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24017_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24017\ses-1\func
['sub-24017', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24017_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24017\ses-1\func
['sub-24017', 'ses-1', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24017_ses-1_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24017\ses-1\func
['sub-24017', 'ses-1', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24017_ses-1_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24017\ses-1\func
['sub-24017', 'ses-1', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24017_ses-1_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24017\ses-1\func
['sub-24017', 'ses-2', 'T1w.json']
Moved sub-24017_ses-2_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24017\ses-2\anat
['sub-24017', 'ses-2', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24017_ses-2_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24017\ses-2\func
['sub-24017', 'ses-2', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24017_ses-2_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24017\ses-2\func
['sub-24017', 'ses-2', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24017_ses-2_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24017\ses-2\func
['sub-24017', 'ses-2', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24017_ses-2_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24017\ses-2\func
['sub-24017', 'ses-2', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24017_ses-2_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24017\ses-2\func
['sub-24021', 'ses-1', 'T1w.json']
Moved sub-24021_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24021\ses-1\anat
['sub-24021', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24021_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24021\ses-1\func
['sub-24021', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24021_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24021\ses-1\func
['sub-24021', 'ses-1', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24021_ses-1_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24021\ses-1\func
['sub-24021', 'ses-1', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24021_ses-1_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24021\ses-1\func
['sub-24021', 'ses-1', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24021_ses-1_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24021\ses-1\func
['sub-24021', 'ses-2', 'T1w.json']
Moved sub-24021_ses-2_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24021\ses-2\anat
['sub-24021', 'ses-2', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24021_ses-2_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24021\ses-2\func
['sub-24021', 'ses-2', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24021_ses-2_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24021\ses-2\func
['sub-24021', 'ses-2', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24021_ses-2_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24021\ses-2\func
['sub-24021', 'ses-2', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24021_ses-2_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24021\ses-2\func
['sub-24021', 'ses-2', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24021_ses-2_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24021\ses-2\func
['sub-24022', 'ses-1', 'T1w.json']
Moved sub-24022_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24022\ses-1\anat
['sub-24022', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24022_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24022\ses-1\func
['sub-24022', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24022_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24022\ses-1\func
['sub-24022', 'ses-1', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24022_ses-1_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24022\ses-1\func
['sub-24022', 'ses-1', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24022_ses-1_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24022\ses-1\func
['sub-24022', 'ses-1', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24022_ses-1_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24022\ses-1\func
['sub-24022', 'ses-2', 'T1w.json']
Moved sub-24022_ses-2_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24022\ses-2\anat
['sub-24022', 'ses-2', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24022_ses-2_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24022\ses-2\func
['sub-24022', 'ses-2', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24022_ses-2_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24022\ses-2\func
['sub-24022', 'ses-2', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24022_ses-2_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24022\ses-2\func
['sub-24022', 'ses-2', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24022_ses-2_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24022\ses-2\func
['sub-24022', 'ses-2', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24022_ses-2_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24022\ses-2\func
['sub-24029', 'ses-1', 'T1w.json']
Moved sub-24029_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24029\ses-1\anat
['sub-24029', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24029_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24029\ses-1\func
['sub-24029', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24029_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24029\ses-1\func
['sub-24029', 'ses-1', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24029_ses-1_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24029\ses-1\func
['sub-24029', 'ses-1', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24029_ses-1_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24029\ses-1\func
['sub-24029', 'ses-1', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24029_ses-1_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24029\ses-1\func
['sub-24029', 'ses-2', 'T1w.json']
Moved sub-24029_ses-2_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24029\ses-2\anat
['sub-24029', 'ses-2', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24029_ses-2_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24029\ses-2\func
['sub-24029', 'ses-2', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24029_ses-2_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24029\ses-2\func
['sub-24029', 'ses-2', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24029_ses-2_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24029\ses-2\func
['sub-24029', 'ses-2', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24029_ses-2_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24029\ses-2\func
['sub-24029', 'ses-2', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24029_ses-2_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24029\ses-2\func
['sub-24033', 'ses-1', 'T1w.json']
Moved sub-24033_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24033\ses-1\anat
['sub-24033', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24033_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24033\ses-1\func
['sub-24033', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24033_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24033\ses-1\func
['sub-24033', 'ses-1', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24033_ses-1_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24033\ses-1\func
['sub-24033', 'ses-1', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24033_ses-1_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24033\ses-1\func
['sub-24033', 'ses-1', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24033_ses-1_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24033\ses-1\func
['sub-24038', 'ses-1', 'T1w.json']
Moved sub-24038_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\anat
['sub-24038', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24038_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\func
['sub-24038', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24038_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\func
['sub-24038', 'ses-1', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24038_ses-1_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\func
['sub-24038', 'ses-1', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24038_ses-1_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\func
['sub-24038', 'ses-1', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24038_ses-1_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\func
['sub-24038', 'ses-2', 'T1w.json']
Moved sub-24038_ses-2_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-2\anat
['sub-24038', 'ses-2', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24038_ses-2_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-2\func
['sub-24038', 'ses-2', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24038_ses-2_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-2\func
['sub-24038', 'ses-2', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24038_ses-2_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-2\func
['sub-24038', 'ses-2', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24038_ses-2_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-2\func
['sub-24038', 'ses-2', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24038_ses-2_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24038\ses-2\func
['sub-24039', 'ses-1', 'T1w.json']
Moved sub-24039_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\anat
['sub-24039', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24039_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\func
['sub-24039', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24039_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\func
['sub-24039', 'ses-1', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24039_ses-1_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\func
['sub-24039', 'ses-1', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24039_ses-1_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\func
['sub-24039', 'ses-1', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24039_ses-1_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\func
['sub-24039', 'ses-2', 'T1w.json']
Moved sub-24039_ses-2_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-2\anat
['sub-24039', 'ses-2', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24039_ses-2_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-2\func
['sub-24039', 'ses-2', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24039_ses-2_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-2\func
['sub-24039', 'ses-2', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24039_ses-2_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-2\func
['sub-24039', 'ses-2', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24039_ses-2_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-2\func
['sub-24039', 'ses-2', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24039_ses-2_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24039\ses-2\func
['sub-24040', 'ses-1', 'T1w.json']
Moved sub-24040_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\anat
['sub-24040', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24040_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\func
['sub-24040', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24040_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\func
['sub-24040', 'ses-1', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24040_ses-1_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\func
['sub-24040', 'ses-1', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24040_ses-1_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\func
['sub-24040', 'ses-1', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24040_ses-1_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\func
['sub-24040', 'ses-2', 'T1w.json']
Moved sub-24040_ses-2_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-2\anat
['sub-24040', 'ses-2', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24040_ses-2_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-2\func
['sub-24040', 'ses-2', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24040_ses-2_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-2\func
['sub-24040', 'ses-2', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24040_ses-2_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-2\func
['sub-24040', 'ses-2', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24040_ses-2_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-2\func
['sub-24040', 'ses-2', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24040_ses-2_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24040\ses-2\func
['sub-24046', 'ses-1', 'T1w.json']
Moved sub-24046_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\anat
['sub-24046', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24046_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\func
['sub-24046', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24046_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\func
['sub-24046', 'ses-1', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24046_ses-1_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\func
['sub-24046', 'ses-1', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24046_ses-1_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\func
['sub-24046', 'ses-1', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24046_ses-1_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\func
['sub-24050', 'ses-1', 'T1w.json']
Moved sub-24050_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\anat
['sub-24050', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24050_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\func
['sub-24050', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24050_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\func
['sub-24050', 'ses-1', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24050_ses-1_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\func
['sub-24050', 'ses-1', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24050_ses-1_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\func
['sub-24050', 'ses-1', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24050_ses-1_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\func
['sub-24050', 'ses-2', 'T1w.json']
Moved sub-24050_ses-2_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-2\anat
['sub-24050', 'ses-2', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24050_ses-2_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-2\func
['sub-24050', 'ses-2', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24050_ses-2_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-2\func
['sub-24050', 'ses-2', 'task-rest', 'echo-3', 'bold.json']
Moved sub-24050_ses-2_task-rest_echo-3_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-2\func
['sub-24050', 'ses-2', 'task-TAU2', 'run-1', 'bold.json']
Moved sub-24050_ses-2_task-TAU2_run-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-2\func
['sub-24050', 'ses-2', 'task-TAU2', 'run-2', 'bold.json']
Moved sub-24050_ses-2_task-TAU2_run-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24050\ses-2\func
['sub-24067', 'ses-1', 'T1w.json']
Moved sub-24067_ses-1_T1w.json to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-1\anat
['sub-24067', 'ses-1', 'task-rest', 'echo-1', 'bold.json']
Moved sub-24067_ses-1_task-rest_echo-1_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-1\func
['sub-24067', 'ses-1', 'task-rest', 'echo-2', 'bold.json']
Moved sub-24067_ses-1_task-rest_echo-2_bold.json to ..\Pediatric_Anxiety_Disorder\sub-24067\ses-1\func
['sub-24067', 'ses-1', 'task-rest', 'echo-3', 'bold.json']

In [5]:
c = 0

for sub in os.listdir(base):
    sub_path = os.path.join(base, sub)
    if not (os.path.isdir(sub_path) and sub.startswith('sub')):
        continue

    c += 1
    ses_path = os.path.join(sub_path, 'ses-1')

    anat_task = os.path.join(ses_path, 'anat_task')
    anat_rest = os.path.join(ses_path, 'anat_rest')

    if os.path.exists(anat_task):
        shutil.rmtree(anat_task)
        print(f"Deleted {anat_task}")

    if os.path.exists(anat_rest):
        shutil.rmtree(anat_rest)
        print(f"Deleted {anat_rest}")

print("Subjects processed:", c)

Deleted ..\Pediatric_Anxiety_Disorder\sub-22380\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22380\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22381\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22381\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22475\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22475\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22477\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22477\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22482\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22482\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22487\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22487\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22494\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22494\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22532\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22532\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22536\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22536\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22587\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22587\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22600\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22600\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22623\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22623\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22630\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22630\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22686\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22686\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22687\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22687\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22727\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22727\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22734\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22734\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22818\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22818\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22829\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22829\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22831\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22831\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22847\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22847\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22860\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22860\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22862\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22862\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22871\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22871\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22873\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22873\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22906\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22906\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22956\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22956\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23010\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23010\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23014\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23014\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23028\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23028\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23044\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23044\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23072\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23072\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23123\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23123\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23257\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23257\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23261\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23261\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23294\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23294\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23303\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23303\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23314\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23314\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23317\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23317\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23342\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23342\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23353\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23353\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23362\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23362\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23376\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23376\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23381\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23381\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23382\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23382\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23386\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23386\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23392\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23392\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23407\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23407\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23432\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23432\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23442\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23442\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23480\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23480\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23483\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23483\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23485\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23485\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23494\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23494\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23501\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23501\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23524\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23524\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23532\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23532\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23534\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23534\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23545\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23545\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23559\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23559\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23567\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23567\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23568\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23568\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23572\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23572\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23584\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23584\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23601\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23601\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23622\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23622\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23629\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23629\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23631\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23631\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23664\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23664\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23690\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23690\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23735\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23735\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23749\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23749\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23762\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23762\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23779\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23779\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23822\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23822\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23842\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23842\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23855\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23855\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23865\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23865\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23871\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23871\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23878\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23878\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23883\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23883\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23892\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23892\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23910\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23910\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23923\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23923\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23925\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23925\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23946\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23946\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23971\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23971\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23972\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23972\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23979\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23979\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23985\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23985\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23986\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23986\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23987\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23987\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23991\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23991\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-23996\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-23996\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24004\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24004\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24015\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24015\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24017\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24017\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24021\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24021\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24022\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24022\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24029\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24029\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24033\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24033\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24038\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24039\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24040\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24046\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24050\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24067\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24067\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24073\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24073\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24089\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24089\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24091\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24091\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24106\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24106\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24115\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24115\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24118\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24118\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24127\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24127\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24139\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24139\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24142\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24142\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24145\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24145\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24146\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24146\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24148\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24148\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24151\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24151\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24182\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24182\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24197\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24197\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24198\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24198\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24212\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24212\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24217\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24217\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24236\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24236\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24240\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24240\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24260\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24260\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24270\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24270\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24275\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24275\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24276\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24276\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24300\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24300\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-24353\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-24353\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22366\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22366\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22346\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22346\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22353\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22353\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22354\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22354\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22365\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22365\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22295\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22295\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22172\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22172\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22268\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22268\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22281\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22281\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-22286\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-22286\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-21508\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-21508\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-21214\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-21214\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-21100\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-21100\ses-1\anat_rest
Deleted ..\Pediatric_Anxiety_Disorder\sub-20725 - without reorienting\ses-1\anat_task
Deleted ..\Pediatric_Anxiety_Disorder\sub-20725 - without reorienting\ses-1\anat_rest
Subjects processed: 150

In [4]:
c = 0

for sub in os.listdir(base):
    sub_path = os.path.join(base, sub)
    if not (os.path.isdir(sub_path) and sub.startswith('sub')):
        continue
    print(sub_path)
    
    c += 1
    ses_path = os.path.join(sub_path, 'ses-1')

    anat_path = os.path.join(ses_path, 'anat')
    anat_task = os.path.join(ses_path, 'anat_task')
    anat_rest = os.path.join(ses_path, 'anat_rest')

    if not os.path.exists(anat_task):
        shutil.copytree(anat_path, anat_task)

    if not os.path.exists(anat_rest):
        shutil.copytree(anat_path, anat_rest)

print("Subjects processed:", c)

..\Pediatric_Anxiety_Disorder\sub-22380
..\Pediatric_Anxiety_Disorder\sub-22381
..\Pediatric_Anxiety_Disorder\sub-22475
..\Pediatric_Anxiety_Disorder\sub-22477
..\Pediatric_Anxiety_Disorder\sub-22482
..\Pediatric_Anxiety_Disorder\sub-22487
..\Pediatric_Anxiety_Disorder\sub-22494
..\Pediatric_Anxiety_Disorder\sub-22532
..\Pediatric_Anxiety_Disorder\sub-22536
..\Pediatric_Anxiety_Disorder\sub-22587
..\Pediatric_Anxiety_Disorder\sub-22600
..\Pediatric_Anxiety_Disorder\sub-22623
..\Pediatric_Anxiety_Disorder\sub-22630
..\Pediatric_Anxiety_Disorder\sub-22686
..\Pediatric_Anxiety_Disorder\sub-22687
..\Pediatric_Anxiety_Disorder\sub-22727
..\Pediatric_Anxiety_Disorder\sub-22734
..\Pediatric_Anxiety_Disorder\sub-22818
..\Pediatric_Anxiety_Disorder\sub-22829
..\Pediatric_Anxiety_Disorder\sub-22831
..\Pediatric_Anxiety_Disorder\sub-22847
..\Pediatric_Anxiety_Disorder\sub-22860
..\Pediatric_Anxiety_Disorder\sub-22862
..\Pediatric_Anxiety_Disorder\sub-22871
..\Pediatric_Anxiety_Disorder\sub-22873
..\Pediatric_Anxiety_Disorder\sub-22906
..\Pediatric_Anxiety_Disorder\sub-22956
..\Pediatric_Anxiety_Disorder\sub-23010
..\Pediatric_Anxiety_Disorder\sub-23014
..\Pediatric_Anxiety_Disorder\sub-23028
..\Pediatric_Anxiety_Disorder\sub-23044
..\Pediatric_Anxiety_Disorder\sub-23072
..\Pediatric_Anxiety_Disorder\sub-23123
..\Pediatric_Anxiety_Disorder\sub-23257
..\Pediatric_Anxiety_Disorder\sub-23261
..\Pediatric_Anxiety_Disorder\sub-23294
..\Pediatric_Anxiety_Disorder\sub-23303
..\Pediatric_Anxiety_Disorder\sub-23314
..\Pediatric_Anxiety_Disorder\sub-23317
..\Pediatric_Anxiety_Disorder\sub-23342
..\Pediatric_Anxiety_Disorder\sub-23353
..\Pediatric_Anxiety_Disorder\sub-23362
..\Pediatric_Anxiety_Disorder\sub-23376
..\Pediatric_Anxiety_Disorder\sub-23381
..\Pediatric_Anxiety_Disorder\sub-23382
..\Pediatric_Anxiety_Disorder\sub-23386
..\Pediatric_Anxiety_Disorder\sub-23392
..\Pediatric_Anxiety_Disorder\sub-23407
..\Pediatric_Anxiety_Disorder\sub-23432
..\Pediatric_Anxiety_Disorder\sub-23442
..\Pediatric_Anxiety_Disorder\sub-23480
..\Pediatric_Anxiety_Disorder\sub-23483
..\Pediatric_Anxiety_Disorder\sub-23485
..\Pediatric_Anxiety_Disorder\sub-23494
..\Pediatric_Anxiety_Disorder\sub-23501
..\Pediatric_Anxiety_Disorder\sub-23524
..\Pediatric_Anxiety_Disorder\sub-23532
..\Pediatric_Anxiety_Disorder\sub-23534
..\Pediatric_Anxiety_Disorder\sub-23545
..\Pediatric_Anxiety_Disorder\sub-23559
..\Pediatric_Anxiety_Disorder\sub-23567
..\Pediatric_Anxiety_Disorder\sub-23568
..\Pediatric_Anxiety_Disorder\sub-23572
..\Pediatric_Anxiety_Disorder\sub-23584
..\Pediatric_Anxiety_Disorder\sub-23601
..\Pediatric_Anxiety_Disorder\sub-23622
..\Pediatric_Anxiety_Disorder\sub-23629
..\Pediatric_Anxiety_Disorder\sub-23631
..\Pediatric_Anxiety_Disorder\sub-23664
..\Pediatric_Anxiety_Disorder\sub-23690
..\Pediatric_Anxiety_Disorder\sub-23735
..\Pediatric_Anxiety_Disorder\sub-23749
..\Pediatric_Anxiety_Disorder\sub-23762
..\Pediatric_Anxiety_Disorder\sub-23779
..\Pediatric_Anxiety_Disorder\sub-23822
..\Pediatric_Anxiety_Disorder\sub-23842
..\Pediatric_Anxiety_Disorder\sub-23855
..\Pediatric_Anxiety_Disorder\sub-23865
..\Pediatric_Anxiety_Disorder\sub-23871
..\Pediatric_Anxiety_Disorder\sub-23878
..\Pediatric_Anxiety_Disorder\sub-23883
..\Pediatric_Anxiety_Disorder\sub-23892
..\Pediatric_Anxiety_Disorder\sub-23910
..\Pediatric_Anxiety_Disorder\sub-23923
..\Pediatric_Anxiety_Disorder\sub-23925
..\Pediatric_Anxiety_Disorder\sub-23946
..\Pediatric_Anxiety_Disorder\sub-23971
..\Pediatric_Anxiety_Disorder\sub-23972
..\Pediatric_Anxiety_Disorder\sub-23979
..\Pediatric_Anxiety_Disorder\sub-23985
..\Pediatric_Anxiety_Disorder\sub-23986
..\Pediatric_Anxiety_Disorder\sub-23987
..\Pediatric_Anxiety_Disorder\sub-23991
..\Pediatric_Anxiety_Disorder\sub-23996
..\Pediatric_Anxiety_Disorder\sub-24004
..\Pediatric_Anxiety_Disorder\sub-24015
..\Pediatric_Anxiety_Disorder\sub-24017
..\Pediatric_Anxiety_Disorder\sub-24021
..\Pediatric_Anxiety_Disorder\sub-24022
..\Pediatric_Anxiety_Disorder\sub-24029
..\Pediatric_Anxiety_Disorder\sub-24033
..\Pediatric_Anxiety_Disorder\sub-24038
..\Pediatric_Anxiety_Disorder\sub-24039
..\Pediatric_Anxiety_Disorder\sub-24040
..\Pediatric_Anxiety_Disorder\sub-24046
..\Pediatric_Anxiety_Disorder\sub-24050
..\Pediatric_Anxiety_Disorder\sub-24067
..\Pediatric_Anxiety_Disorder\sub-24073
..\Pediatric_Anxiety_Disorder\sub-24089
..\Pediatric_Anxiety_Disorder\sub-24091
..\Pediatric_Anxiety_Disorder\sub-24106
..\Pediatric_Anxiety_Disorder\sub-24115
..\Pediatric_Anxiety_Disorder\sub-24118
..\Pediatric_Anxiety_Disorder\sub-24127
..\Pediatric_Anxiety_Disorder\sub-24139
..\Pediatric_Anxiety_Disorder\sub-24142
..\Pediatric_Anxiety_Disorder\sub-24145
..\Pediatric_Anxiety_Disorder\sub-24146
..\Pediatric_Anxiety_Disorder\sub-24148
..\Pediatric_Anxiety_Disorder\sub-24151
..\Pediatric_Anxiety_Disorder\sub-24182
..\Pediatric_Anxiety_Disorder\sub-24197
..\Pediatric_Anxiety_Disorder\sub-24198
..\Pediatric_Anxiety_Disorder\sub-24212
..\Pediatric_Anxiety_Disorder\sub-24217
..\Pediatric_Anxiety_Disorder\sub-24236
..\Pediatric_Anxiety_Disorder\sub-24240
..\Pediatric_Anxiety_Disorder\sub-24260
..\Pediatric_Anxiety_Disorder\sub-24270
..\Pediatric_Anxiety_Disorder\sub-24275
..\Pediatric_Anxiety_Disorder\sub-24276
..\Pediatric_Anxiety_Disorder\sub-24300
..\Pediatric_Anxiety_Disorder\sub-24353
..\Pediatric_Anxiety_Disorder\sub-22366
..\Pediatric_Anxiety_Disorder\sub-22346
..\Pediatric_Anxiety_Disorder\sub-22353
..\Pediatric_Anxiety_Disorder\sub-22354
..\Pediatric_Anxiety_Disorder\sub-22365
..\Pediatric_Anxiety_Disorder\sub-22295
..\Pediatric_Anxiety_Disorder\sub-22172
..\Pediatric_Anxiety_Disorder\sub-22268
..\Pediatric_Anxiety_Disorder\sub-22281
..\Pediatric_Anxiety_Disorder\sub-22286
..\Pediatric_Anxiety_Disorder\sub-21508
..\Pediatric_Anxiety_Disorder\sub-21214
..\Pediatric_Anxiety_Disorder\sub-21100
..\Pediatric_Anxiety_Disorder\sub-20725
..\Pediatric_Anxiety_Disorder\sub-20209
..\Pediatric_Anxiety_Disorder\sub-20131
Subjects processed: 149

In [3]:
c1 = [20131, 20209, 20725, 21100, 21214, 21508, 22268, 22281, 22286, 22295, 22346, 22353, 22354, 22365, 22366, 22380, 22381, 22475, 22477, 22482, 22487, 22494, 22532, 22536, 22587, 22600, 22623, 22630, 22686, 22687, 22727, 22734, 22829, 22831, 22847, 22860, 22862, 22873, 22906, 22956, 23010, 23014, 23028, 23044]
len(c1)

44

In [19]:
count = 0
for subject in c1:
    sub = 'sub-'+str(subject)
    path = os.path.join(base, sub, 'ses-1', 'func')
    flag = False
    for item in os.listdir(path):
        if 'TAU' in item and 'nii' in item:
            print(item)
        if 'rest' in item and 'nii' in item:
            print(item)
        if 'TAU2' in item and 'nii' in item:
            flag = True
    if not flag:
        count += 1
        print(count, "NOT THERE")
    print()

sub-20131_ses-1_task-rest_bold.nii.gz
sub-20131_ses-1_task-TAU1_run-1_bold.nii.gz
sub-20131_ses-1_task-TAU1_run-2_bold.nii.gz
sub-20131_ses-1_task-TAU1_run-1_bold.nii
sub-20131_ses-1_task-TAU1_run-2_bold.nii
sub-20131_ses-1_task-rest_bold.nii
1 NOT THERE

sub-20209_ses-1_task-rest_bold.nii.gz
sub-20209_ses-1_task-TAU1_run-1_bold.nii.gz
sub-20209_ses-1_task-TAU1_run-2_bold.nii.gz
sub-20209_ses-1_task-TAU1_run-1_bold.nii
sub-20209_ses-1_task-TAU1_run-2_bold.nii
sub-20209_ses-1_task-rest_bold.nii
2 NOT THERE

sub-20725_ses-1_task-rest_bold.nii.gz
sub-20725_ses-1_task-TAU1_run-1_bold.nii.gz
sub-20725_ses-1_task-TAU1_run-2_bold.nii.gz
sub-20725_ses-1_task-TAU1_run-1_bold.nii
sub-20725_ses-1_task-TAU1_run-2_bold.nii
sub-20725_ses-1_task-rest_bold.nii
3 NOT THERE

sub-21100_ses-1_task-rest_bold.nii.gz
sub-21100_ses-1_task-rest_echo-1_bold.nii.gz
sub-21100_ses-1_task-rest_echo-2_bold.nii.gz
sub-21100_ses-1_task-rest_echo-3_bold.nii.gz
sub-21100_ses-1_task-TAU1_run-1_bold.nii.gz
sub-21100_ses-1_task-TAU1_run-2_bold.nii.gz
sub-21100_ses-1_task-TAU2_run-1_bold.nii.gz
sub-21100_ses-1_task-TAU2_run-2_bold.nii.gz

sub-21214_ses-1_task-rest_bold.nii.gz
sub-21214_ses-1_task-TAU1_run-1_bold.nii.gz
sub-21214_ses-1_task-TAU1_run-2_bold.nii.gz
sub-21214_ses-1_task-TAU1_run-1_bold.nii
sub-21214_ses-1_task-TAU1_run-2_bold.nii
sub-21214_ses-1_task-rest_bold.nii
4 NOT THERE

sub-21508_ses-1_task-rest_bold.nii.gz
sub-21508_ses-1_task-TAU1_run-1_bold.nii.gz
sub-21508_ses-1_task-TAU1_run-2_bold.nii.gz
sub-21508_ses-1_task-TAU1_run-1_bold.nii
sub-21508_ses-1_task-TAU1_run-2_bold.nii
sub-21508_ses-1_task-rest_bold.nii
5 NOT THERE

sub-22268_ses-1_task-rest_bold.nii.gz
sub-22268_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22268_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22268_ses-1_task-TAU1_run-1_bold.nii
sub-22268_ses-1_task-TAU1_run-2_bold.nii
sub-22268_ses-1_task-rest_bold.nii
6 NOT THERE

sub-22281_ses-1_task-rest_bold.nii.gz
sub-22281_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22281_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22281_ses-1_task-TAU1_run-1_bold.nii
sub-22281_ses-1_task-TAU1_run-2_bold.nii
sub-22281_ses-1_task-rest_bold.nii
7 NOT THERE

sub-22286_ses-1_task-rest_bold.nii.gz
sub-22286_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22286_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22286_ses-1_task-TAU1_run-1_bold.nii
sub-22286_ses-1_task-TAU1_run-2_bold.nii
sub-22286_ses-1_task-rest_bold.nii
8 NOT THERE

sub-22295_ses-1_task-rest_bold.nii.gz
sub-22295_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22295_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22295_ses-1_task-TAU1_run-1_bold.nii
sub-22295_ses-1_task-TAU1_run-2_bold.nii
sub-22295_ses-1_task-rest_bold.nii
9 NOT THERE

sub-22346_ses-1_task-rest_bold.nii.gz
sub-22346_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22346_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22346_ses-1_task-TAU1_run-1_bold.nii
sub-22346_ses-1_task-TAU1_run-2_bold.nii
sub-22346_ses-1_task-rest_bold.nii
10 NOT THERE

sub-22353_ses-1_task-rest_bold.nii.gz
sub-22353_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22353_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22353_ses-1_task-TAU1_run-1_bold.nii
sub-22353_ses-1_task-TAU1_run-2_bold.nii
sub-22353_ses-1_task-rest_bold.nii
11 NOT THERE

sub-22354_ses-1_task-rest_bold.nii.gz
sub-22354_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22354_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22354_ses-1_task-TAU1_run-1_bold.nii
sub-22354_ses-1_task-TAU1_run-2_bold.nii
sub-22354_ses-1_task-rest_bold.nii
12 NOT THERE

sub-22365_ses-1_task-rest_bold.nii.gz
sub-22365_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22365_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22365_ses-1_task-TAU1_run-1_bold.nii
sub-22365_ses-1_task-TAU1_run-2_bold.nii
sub-22365_ses-1_task-rest_bold.nii
13 NOT THERE

sub-22366_ses-1_task-rest_bold.nii.gz
sub-22366_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22366_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22366_ses-1_task-TAU1_run-1_bold.nii
sub-22366_ses-1_task-TAU1_run-2_bold.nii
sub-22366_ses-1_task-rest_bold.nii
14 NOT THERE

sub-22380_ses-1_task-rest_bold.nii.gz
sub-22380_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22380_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22380_ses-1_task-TAU1_run-1_bold.nii
sub-22380_ses-1_task-TAU1_run-2_bold.nii
sub-22380_ses-1_task-rest_bold.nii
15 NOT THERE

sub-22381_ses-1_task-rest_bold.nii.gz
sub-22381_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22381_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22381_ses-1_task-TAU1_run-1_bold.nii
sub-22381_ses-1_task-TAU1_run-2_bold.nii
sub-22381_ses-1_task-rest_bold.nii
16 NOT THERE

sub-22475_ses-1_task-rest_bold.nii.gz
sub-22475_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22475_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22475_ses-1_task-TAU1_run-1_bold.nii
sub-22475_ses-1_task-TAU1_run-2_bold.nii
sub-22475_ses-1_task-rest_bold.nii
17 NOT THERE

sub-22477_ses-1_task-rest_bold.nii.gz
sub-22477_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22477_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22477_ses-1_task-TAU1_run-1_bold.nii
sub-22477_ses-1_task-TAU1_run-2_bold.nii
sub-22477_ses-1_task-rest_bold.nii
18 NOT THERE

sub-22482_ses-1_task-rest_bold.nii.gz
sub-22482_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22482_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22482_ses-1_task-TAU1_run-1_bold.nii
sub-22482_ses-1_task-TAU1_run-2_bold.nii
sub-22482_ses-1_task-rest_bold.nii
19 NOT THERE

sub-22487_ses-1_task-rest_bold.nii.gz
sub-22487_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22487_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22487_ses-1_task-TAU1_run-1_bold.nii
sub-22487_ses-1_task-TAU1_run-2_bold.nii
sub-22487_ses-1_task-rest_bold.nii
20 NOT THERE

sub-22494_ses-1_task-rest_bold.nii.gz
sub-22494_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22494_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22494_ses-1_task-TAU1_run-1_bold.nii
sub-22494_ses-1_task-TAU1_run-2_bold.nii
sub-22494_ses-1_task-rest_bold.nii
21 NOT THERE

sub-22532_ses-1_task-rest_bold.nii.gz
sub-22532_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22532_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22532_ses-1_task-TAU1_run-1_bold.nii
sub-22532_ses-1_task-TAU1_run-2_bold.nii
sub-22532_ses-1_task-rest_bold.nii
22 NOT THERE

sub-22536_ses-1_task-rest_bold.nii.gz
sub-22536_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22536_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22536_ses-1_task-TAU1_run-1_bold.nii
sub-22536_ses-1_task-TAU1_run-2_bold.nii
sub-22536_ses-1_task-rest_bold.nii
23 NOT THERE

sub-22587_ses-1_task-rest_bold.nii.gz
sub-22587_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22587_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22587_ses-1_task-TAU1_run-1_bold.nii
sub-22587_ses-1_task-TAU1_run-2_bold.nii
sub-22587_ses-1_task-rest_bold.nii
24 NOT THERE

sub-22600_ses-1_task-rest_bold.nii.gz
sub-22600_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22600_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22600_ses-1_task-TAU1_run-1_bold.nii
sub-22600_ses-1_task-TAU1_run-2_bold.nii
sub-22600_ses-1_task-rest_bold.nii
25 NOT THERE

sub-22623_ses-1_task-rest_bold.nii.gz
sub-22623_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22623_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22623_ses-1_task-TAU1_run-1_bold.nii
sub-22623_ses-1_task-TAU1_run-2_bold.nii
sub-22623_ses-1_task-rest_bold.nii
26 NOT THERE

sub-22630_ses-1_task-rest_bold.nii.gz
sub-22630_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22630_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22630_ses-1_task-TAU1_run-1_bold.nii
sub-22630_ses-1_task-TAU1_run-2_bold.nii
sub-22630_ses-1_task-rest_bold.nii
27 NOT THERE

sub-22686_ses-1_task-rest_bold.nii.gz
sub-22686_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22686_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22686_ses-1_task-TAU1_run-1_bold.nii
sub-22686_ses-1_task-TAU1_run-2_bold.nii
sub-22686_ses-1_task-rest_bold.nii
28 NOT THERE

sub-22687_ses-1_task-rest_bold.nii.gz
sub-22687_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22687_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22687_ses-1_task-TAU1_run-1_bold.nii
sub-22687_ses-1_task-TAU1_run-2_bold.nii
sub-22687_ses-1_task-rest_bold.nii
29 NOT THERE

sub-22727_ses-1_task-rest_bold.nii.gz
sub-22727_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22727_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22727_ses-1_task-TAU1_run-1_bold.nii
sub-22727_ses-1_task-TAU1_run-2_bold.nii
sub-22727_ses-1_task-rest_bold.nii
30 NOT THERE

sub-22734_ses-1_task-rest_bold.nii.gz
sub-22734_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22734_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22734_ses-1_task-TAU1_run-1_bold.nii
sub-22734_ses-1_task-TAU1_run-2_bold.nii
sub-22734_ses-1_task-rest_bold.nii
31 NOT THERE

sub-22829_ses-1_task-rest_bold.nii.gz
sub-22829_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22829_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22829_ses-1_task-TAU1_run-1_bold.nii
sub-22829_ses-1_task-TAU1_run-2_bold.nii
sub-22829_ses-1_task-rest_bold.nii
32 NOT THERE

sub-22831_ses-1_task-rest_bold.nii.gz
sub-22831_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22831_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22831_ses-1_task-TAU1_run-1_bold.nii
sub-22831_ses-1_task-TAU1_run-2_bold.nii
sub-22831_ses-1_task-rest_bold.nii
33 NOT THERE

sub-22847_ses-1_task-rest_bold.nii.gz
sub-22847_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22847_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22847_ses-1_task-TAU1_run-1_bold.nii
sub-22847_ses-1_task-TAU1_run-2_bold.nii
sub-22847_ses-1_task-rest_bold.nii
34 NOT THERE

sub-22860_ses-1_task-rest_bold.nii.gz
sub-22860_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22860_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22860_ses-1_task-TAU1_run-1_bold.nii
sub-22860_ses-1_task-TAU1_run-2_bold.nii
sub-22860_ses-1_task-rest_bold.nii
35 NOT THERE

sub-22862_ses-1_task-rest_bold.nii.gz
sub-22862_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22862_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22862_ses-1_task-TAU1_run-1_bold.nii
sub-22862_ses-1_task-TAU1_run-2_bold.nii
sub-22862_ses-1_task-rest_bold.nii
36 NOT THERE

sub-22873_ses-1_task-rest_bold.nii.gz
sub-22873_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22873_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22873_ses-1_task-TAU1_run-1_bold.nii
sub-22873_ses-1_task-TAU1_run-2_bold.nii
sub-22873_ses-1_task-rest_bold.nii
37 NOT THERE

sub-22906_ses-1_task-rest_bold.nii.gz
sub-22906_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22906_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22906_ses-1_task-TAU1_run-1_bold.nii
sub-22906_ses-1_task-TAU1_run-2_bold.nii
sub-22906_ses-1_task-rest_bold.nii
38 NOT THERE

sub-22956_ses-1_task-rest_bold.nii.gz
sub-22956_ses-1_task-TAU1_run-1_bold.nii.gz
sub-22956_ses-1_task-TAU1_run-2_bold.nii.gz
sub-22956_ses-1_task-TAU1_run-1_bold.nii
sub-22956_ses-1_task-TAU1_run-2_bold.nii
sub-22956_ses-1_task-rest_bold.nii
39 NOT THERE

sub-23010_ses-1_task-rest_bold.nii.gz
sub-23010_ses-1_task-TAU1_run-1_bold.nii.gz
sub-23010_ses-1_task-TAU1_run-2_bold.nii.gz
sub-23010_ses-1_task-TAU1_run-1_bold.nii
sub-23010_ses-1_task-TAU1_run-2_bold.nii
sub-23010_ses-1_task-rest_bold.nii
40 NOT THERE

sub-23014_ses-1_task-rest_bold.nii.gz
sub-23014_ses-1_task-TAU1_run-1_bold.nii.gz
sub-23014_ses-1_task-TAU1_run-2_bold.nii.gz
sub-23014_ses-1_task-TAU1_run-1_bold.nii
sub-23014_ses-1_task-TAU1_run-2_bold.nii
sub-23014_ses-1_task-rest_bold.nii
41 NOT THERE

sub-23028_ses-1_task-rest_bold.nii.gz
sub-23028_ses-1_task-TAU1_run-1_bold.nii.gz
sub-23028_ses-1_task-TAU1_run-2_bold.nii.gz
sub-23028_ses-1_task-TAU1_run-1_bold.nii
sub-23028_ses-1_task-TAU1_run-2_bold.nii
sub-23028_ses-1_task-rest_bold.nii
42 NOT THERE

sub-23044_ses-1_task-rest_bold.nii.gz
sub-23044_ses-1_task-TAU1_run-1_bold.nii.gz
sub-23044_ses-1_task-TAU1_run-2_bold.nii.gz
sub-23044_ses-1_task-TAU1_run-1_bold.nii
sub-23044_ses-1_task-TAU1_run-2_bold.nii
sub-23044_ses-1_task-rest_bold.nii
43 NOT THERE

In [17]:
c2 = [22172, 22818, 22871, 23072, 23123, 23257, 23261, 23294, 23303, 23314, 23317, 23342, 23353, 23362, 23376, 23381, 23382, 23386, 23392, 23407, 23432, 23442, 23480, 23483, 23485, 23494, 23501, 23524, 23532, 23534, 23545, 23559, 23567, 23568, 23572, 23584, 23601, 23622, 23629, 23631, 23664, 23690, 23735, 23749, 23762, 23779, 23822, 23842, 23855, 23865, 23871, 23878, 23883, 23892, 23910, 23923, 23925, 23946, 23971, 23972, 23979, 23985, 23986, 23987, 23991, 23996, 24004, 24015, 24017, 24021, 24022, 24029, 24033, 24038, 24039, 24040, 24046, 24050, 24067, 24073, 24089, 24091, 24106, 24115, 24118, 24127, 24139, 24142, 24145, 24146, 24148, 24151, 24182, 24197, 24198, 24212, 24217, 24236, 24240, 24260, 24270, 24275, 24276, 24300, 24353]
len(c2)

105

In [18]:
count = 0
for subject in c2:
    sub = 'sub-'+str(subject)
    path = os.path.join(base, sub, 'ses-1', 'func')
    flag = False
    for item in os.listdir(path):
        if 'TAU' in item and 'nii' in item:
            print(item)
        if 'rest' in item and 'nii' in item:
            print(item)
        if 'TAU1' in item and 'nii' in item:
            flag = True
    if not flag:
        count += 1
        print(count, "NOT THERE")
    print()

sub-22172_ses-1_task-rest_echo-1_bold.nii.gz
sub-22172_ses-1_task-rest_echo-2_bold.nii.gz
sub-22172_ses-1_task-rest_echo-3_bold.nii.gz
sub-22172_ses-1_task-TAU2_run-1_bold.nii.gz
sub-22172_ses-1_task-TAU2_run-2_bold.nii.gz
sub-22172_ses-1_task-TAU2_run-1_bold.nii
sub-22172_ses-1_task-TAU2_run-2_bold.nii
sub-22172_ses-1_task-rest_echo-1_bold.nii
sub-22172_ses-1_task-rest_echo-2_bold.nii
sub-22172_ses-1_task-rest_echo-3_bold.nii
1 NOT THERE

sub-22818_ses-1_task-rest_echo-1_bold.nii.gz
sub-22818_ses-1_task-rest_echo-2_bold.nii.gz
sub-22818_ses-1_task-rest_echo-3_bold.nii.gz
sub-22818_ses-1_task-TAU2_run-1_bold.nii.gz
sub-22818_ses-1_task-TAU2_run-2_bold.nii.gz
sub-22818_ses-1_task-TAU2_run-1_bold.nii
sub-22818_ses-1_task-TAU2_run-2_bold.nii
sub-22818_ses-1_task-rest_echo-1_bold.nii
sub-22818_ses-1_task-rest_echo-2_bold.nii
sub-22818_ses-1_task-rest_echo-3_bold.nii
2 NOT THERE

sub-22871_ses-1_task-rest_echo-1_bold.nii.gz
sub-22871_ses-1_task-rest_echo-2_bold.nii.gz
sub-22871_ses-1_task-rest_echo-3_bold.nii.gz
sub-22871_ses-1_task-TAU2_run-1_bold.nii.gz
sub-22871_ses-1_task-TAU2_run-2_bold.nii.gz
sub-22871_ses-1_task-TAU2_run-1_bold.nii
sub-22871_ses-1_task-TAU2_run-2_bold.nii
sub-22871_ses-1_task-rest_echo-1_bold.nii
sub-22871_ses-1_task-rest_echo-2_bold.nii
sub-22871_ses-1_task-rest_echo-3_bold.nii
3 NOT THERE

sub-23072_ses-1_task-rest_echo-1_bold.nii.gz
sub-23072_ses-1_task-rest_echo-2_bold.nii.gz
sub-23072_ses-1_task-rest_echo-3_bold.nii.gz
sub-23072_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23072_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23072_ses-1_task-TAU2_run-1_bold.nii
sub-23072_ses-1_task-TAU2_run-2_bold.nii
sub-23072_ses-1_task-rest_echo-1_bold.nii
sub-23072_ses-1_task-rest_echo-2_bold.nii
sub-23072_ses-1_task-rest_echo-3_bold.nii
4 NOT THERE

sub-23123_ses-1_task-rest_echo-1_bold.nii.gz
sub-23123_ses-1_task-rest_echo-2_bold.nii.gz
sub-23123_ses-1_task-rest_echo-3_bold.nii.gz
sub-23123_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23123_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23123_ses-1_task-TAU2_run-1_bold.nii
sub-23123_ses-1_task-TAU2_run-2_bold.nii
sub-23123_ses-1_task-rest_echo-1_bold.nii
sub-23123_ses-1_task-rest_echo-2_bold.nii
sub-23123_ses-1_task-rest_echo-3_bold.nii
5 NOT THERE

sub-23257_ses-1_task-rest_echo-1_bold.nii.gz
sub-23257_ses-1_task-rest_echo-2_bold.nii.gz
sub-23257_ses-1_task-rest_echo-3_bold.nii.gz
sub-23257_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23257_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23257_ses-1_task-TAU2_run-1_bold.nii
sub-23257_ses-1_task-TAU2_run-2_bold.nii
sub-23257_ses-1_task-rest_echo-1_bold.nii
sub-23257_ses-1_task-rest_echo-2_bold.nii
sub-23257_ses-1_task-rest_echo-3_bold.nii
6 NOT THERE

sub-23261_ses-1_task-rest_echo-1_bold.nii.gz
sub-23261_ses-1_task-rest_echo-2_bold.nii.gz
sub-23261_ses-1_task-rest_echo-3_bold.nii.gz
sub-23261_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23261_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23261_ses-1_task-TAU2_run-1_bold.nii
sub-23261_ses-1_task-TAU2_run-2_bold.nii
sub-23261_ses-1_task-rest_echo-1_bold.nii
sub-23261_ses-1_task-rest_echo-2_bold.nii
sub-23261_ses-1_task-rest_echo-3_bold.nii
7 NOT THERE

sub-23294_ses-1_task-rest_echo-1_bold.nii.gz
sub-23294_ses-1_task-rest_echo-2_bold.nii.gz
sub-23294_ses-1_task-rest_echo-3_bold.nii.gz
sub-23294_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23294_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23294_ses-1_task-TAU2_run-1_bold.nii
sub-23294_ses-1_task-TAU2_run-2_bold.nii
sub-23294_ses-1_task-rest_echo-1_bold.nii
sub-23294_ses-1_task-rest_echo-2_bold.nii
sub-23294_ses-1_task-rest_echo-3_bold.nii
8 NOT THERE

sub-23303_ses-1_task-rest_echo-1_bold.nii.gz
sub-23303_ses-1_task-rest_echo-2_bold.nii.gz
sub-23303_ses-1_task-rest_echo-3_bold.nii.gz
sub-23303_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23303_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23303_ses-1_task-TAU2_run-1_bold.nii
sub-23303_ses-1_task-TAU2_run-2_bold.nii
sub-23303_ses-1_task-rest_echo-1_bold.nii
sub-23303_ses-1_task-rest_echo-2_bold.nii
sub-23303_ses-1_task-rest_echo-3_bold.nii
9 NOT THERE

sub-23314_ses-1_task-rest_echo-1_bold.nii.gz
sub-23314_ses-1_task-rest_echo-2_bold.nii.gz
sub-23314_ses-1_task-rest_echo-3_bold.nii.gz
sub-23314_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23314_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23314_ses-1_task-TAU2_run-1_bold.nii
sub-23314_ses-1_task-TAU2_run-2_bold.nii
sub-23314_ses-1_task-rest_echo-1_bold.nii
sub-23314_ses-1_task-rest_echo-2_bold.nii
sub-23314_ses-1_task-rest_echo-3_bold.nii
10 NOT THERE

sub-23317_ses-1_task-rest_echo-1_bold.nii.gz
sub-23317_ses-1_task-rest_echo-2_bold.nii.gz
sub-23317_ses-1_task-rest_echo-3_bold.nii.gz
sub-23317_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23317_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23317_ses-1_task-TAU2_run-1_bold.nii
sub-23317_ses-1_task-TAU2_run-2_bold.nii
sub-23317_ses-1_task-rest_echo-1_bold.nii
sub-23317_ses-1_task-rest_echo-2_bold.nii
sub-23317_ses-1_task-rest_echo-3_bold.nii
11 NOT THERE

sub-23342_ses-1_task-rest_echo-1_bold.nii.gz
sub-23342_ses-1_task-rest_echo-2_bold.nii.gz
sub-23342_ses-1_task-rest_echo-3_bold.nii.gz
sub-23342_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23342_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23342_ses-1_task-TAU2_run-1_bold.nii
sub-23342_ses-1_task-TAU2_run-2_bold.nii
sub-23342_ses-1_task-rest_echo-1_bold.nii
sub-23342_ses-1_task-rest_echo-2_bold.nii
sub-23342_ses-1_task-rest_echo-3_bold.nii
12 NOT THERE

sub-23353_ses-1_task-rest_echo-1_bold.nii.gz
sub-23353_ses-1_task-rest_echo-2_bold.nii.gz
sub-23353_ses-1_task-rest_echo-3_bold.nii.gz
sub-23353_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23353_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23353_ses-1_task-TAU2_run-1_bold.nii
sub-23353_ses-1_task-TAU2_run-2_bold.nii
sub-23353_ses-1_task-rest_echo-1_bold.nii
sub-23353_ses-1_task-rest_echo-2_bold.nii
sub-23353_ses-1_task-rest_echo-3_bold.nii
13 NOT THERE

sub-23362_ses-1_task-rest_echo-1_bold.nii.gz
sub-23362_ses-1_task-rest_echo-2_bold.nii.gz
sub-23362_ses-1_task-rest_echo-3_bold.nii.gz
sub-23362_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23362_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23362_ses-1_task-TAU2_run-1_bold.nii
sub-23362_ses-1_task-TAU2_run-2_bold.nii
sub-23362_ses-1_task-rest_echo-1_bold.nii
sub-23362_ses-1_task-rest_echo-2_bold.nii
sub-23362_ses-1_task-rest_echo-3_bold.nii
14 NOT THERE

sub-23376_ses-1_task-rest_echo-1_bold.nii.gz
sub-23376_ses-1_task-rest_echo-2_bold.nii.gz
sub-23376_ses-1_task-rest_echo-3_bold.nii.gz
sub-23376_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23376_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23376_ses-1_task-TAU2_run-1_bold.nii
sub-23376_ses-1_task-TAU2_run-2_bold.nii
sub-23376_ses-1_task-rest_echo-1_bold.nii
sub-23376_ses-1_task-rest_echo-2_bold.nii
sub-23376_ses-1_task-rest_echo-3_bold.nii
15 NOT THERE

sub-23381_ses-1_task-rest_echo-1_bold.nii.gz
sub-23381_ses-1_task-rest_echo-2_bold.nii.gz
sub-23381_ses-1_task-rest_echo-3_bold.nii.gz
sub-23381_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23381_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23381_ses-1_task-TAU2_run-1_bold.nii
sub-23381_ses-1_task-TAU2_run-2_bold.nii
sub-23381_ses-1_task-rest_echo-1_bold.nii
sub-23381_ses-1_task-rest_echo-2_bold.nii
sub-23381_ses-1_task-rest_echo-3_bold.nii
16 NOT THERE

sub-23382_ses-1_task-rest_echo-1_bold.nii.gz
sub-23382_ses-1_task-rest_echo-2_bold.nii.gz
sub-23382_ses-1_task-rest_echo-3_bold.nii.gz
sub-23382_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23382_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23382_ses-1_task-TAU2_run-1_bold.nii
sub-23382_ses-1_task-TAU2_run-2_bold.nii
sub-23382_ses-1_task-rest_echo-1_bold.nii
sub-23382_ses-1_task-rest_echo-2_bold.nii
sub-23382_ses-1_task-rest_echo-3_bold.nii
17 NOT THERE

sub-23386_ses-1_task-rest_echo-1_bold.nii.gz
sub-23386_ses-1_task-rest_echo-2_bold.nii.gz
sub-23386_ses-1_task-rest_echo-3_bold.nii.gz
sub-23386_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23386_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23386_ses-1_task-TAU2_run-1_bold.nii
sub-23386_ses-1_task-TAU2_run-2_bold.nii
sub-23386_ses-1_task-rest_echo-1_bold.nii
sub-23386_ses-1_task-rest_echo-2_bold.nii
sub-23386_ses-1_task-rest_echo-3_bold.nii
18 NOT THERE

sub-23392_ses-1_task-rest_echo-1_bold.nii.gz
sub-23392_ses-1_task-rest_echo-2_bold.nii.gz
sub-23392_ses-1_task-rest_echo-3_bold.nii.gz
sub-23392_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23392_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23392_ses-1_task-TAU2_run-1_bold.nii
sub-23392_ses-1_task-TAU2_run-2_bold.nii
sub-23392_ses-1_task-rest_echo-1_bold.nii
sub-23392_ses-1_task-rest_echo-2_bold.nii
sub-23392_ses-1_task-rest_echo-3_bold.nii
19 NOT THERE

sub-23407_ses-1_task-rest_echo-1_bold.nii.gz
sub-23407_ses-1_task-rest_echo-2_bold.nii.gz
sub-23407_ses-1_task-rest_echo-3_bold.nii.gz
sub-23407_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23407_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23407_ses-1_task-TAU2_run-1_bold.nii
sub-23407_ses-1_task-TAU2_run-2_bold.nii
sub-23407_ses-1_task-rest_echo-1_bold.nii
sub-23407_ses-1_task-rest_echo-2_bold.nii
sub-23407_ses-1_task-rest_echo-3_bold.nii
20 NOT THERE

sub-23432_ses-1_task-rest_echo-1_bold.nii.gz
sub-23432_ses-1_task-rest_echo-2_bold.nii.gz
sub-23432_ses-1_task-rest_echo-3_bold.nii.gz
sub-23432_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23432_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23432_ses-1_task-TAU2_run-1_bold.nii
sub-23432_ses-1_task-TAU2_run-2_bold.nii
sub-23432_ses-1_task-rest_echo-1_bold.nii
sub-23432_ses-1_task-rest_echo-2_bold.nii
sub-23432_ses-1_task-rest_echo-3_bold.nii
21 NOT THERE

sub-23442_ses-1_task-rest_echo-1_bold.nii.gz
sub-23442_ses-1_task-rest_echo-2_bold.nii.gz
sub-23442_ses-1_task-rest_echo-3_bold.nii.gz
sub-23442_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23442_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23442_ses-1_task-TAU2_run-1_bold.nii
sub-23442_ses-1_task-TAU2_run-2_bold.nii
sub-23442_ses-1_task-rest_echo-1_bold.nii
sub-23442_ses-1_task-rest_echo-2_bold.nii
sub-23442_ses-1_task-rest_echo-3_bold.nii
22 NOT THERE

sub-23480_ses-1_task-rest_echo-1_bold.nii.gz
sub-23480_ses-1_task-rest_echo-2_bold.nii.gz
sub-23480_ses-1_task-rest_echo-3_bold.nii.gz
sub-23480_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23480_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23480_ses-1_task-TAU2_run-1_bold.nii
sub-23480_ses-1_task-TAU2_run-2_bold.nii
sub-23480_ses-1_task-rest_echo-1_bold.nii
sub-23480_ses-1_task-rest_echo-2_bold.nii
sub-23480_ses-1_task-rest_echo-3_bold.nii
23 NOT THERE

sub-23483_ses-1_task-rest_echo-1_bold.nii.gz
sub-23483_ses-1_task-rest_echo-2_bold.nii.gz
sub-23483_ses-1_task-rest_echo-3_bold.nii.gz
sub-23483_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23483_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23483_ses-1_task-TAU2_run-1_bold.nii
sub-23483_ses-1_task-TAU2_run-2_bold.nii
sub-23483_ses-1_task-rest_echo-1_bold.nii
sub-23483_ses-1_task-rest_echo-2_bold.nii
sub-23483_ses-1_task-rest_echo-3_bold.nii
24 NOT THERE

sub-23485_ses-1_task-rest_echo-1_bold.nii.gz
sub-23485_ses-1_task-rest_echo-2_bold.nii.gz
sub-23485_ses-1_task-rest_echo-3_bold.nii.gz
sub-23485_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23485_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23485_ses-1_task-TAU2_run-1_bold.nii
sub-23485_ses-1_task-TAU2_run-2_bold.nii
sub-23485_ses-1_task-rest_echo-1_bold.nii
sub-23485_ses-1_task-rest_echo-2_bold.nii
sub-23485_ses-1_task-rest_echo-3_bold.nii
25 NOT THERE

sub-23494_ses-1_task-rest_echo-1_bold.nii.gz
sub-23494_ses-1_task-rest_echo-2_bold.nii.gz
sub-23494_ses-1_task-rest_echo-3_bold.nii.gz
sub-23494_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23494_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23494_ses-1_task-TAU2_run-1_bold.nii
sub-23494_ses-1_task-TAU2_run-2_bold.nii
sub-23494_ses-1_task-rest_echo-1_bold.nii
sub-23494_ses-1_task-rest_echo-2_bold.nii
sub-23494_ses-1_task-rest_echo-3_bold.nii
26 NOT THERE

sub-23501_ses-1_task-rest_echo-1_bold.nii.gz
sub-23501_ses-1_task-rest_echo-2_bold.nii.gz
sub-23501_ses-1_task-rest_echo-3_bold.nii.gz
sub-23501_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23501_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23501_ses-1_task-TAU2_run-1_bold.nii
sub-23501_ses-1_task-TAU2_run-2_bold.nii
sub-23501_ses-1_task-rest_echo-1_bold.nii
sub-23501_ses-1_task-rest_echo-2_bold.nii
sub-23501_ses-1_task-rest_echo-3_bold.nii
27 NOT THERE

sub-23524_ses-1_task-rest_echo-1_bold.nii.gz
sub-23524_ses-1_task-rest_echo-2_bold.nii.gz
sub-23524_ses-1_task-rest_echo-3_bold.nii.gz
sub-23524_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23524_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23524_ses-1_task-TAU2_run-1_bold.nii
sub-23524_ses-1_task-TAU2_run-2_bold.nii
sub-23524_ses-1_task-rest_echo-1_bold.nii
sub-23524_ses-1_task-rest_echo-2_bold.nii
sub-23524_ses-1_task-rest_echo-3_bold.nii
28 NOT THERE

sub-23532_ses-1_task-rest_echo-1_bold.nii.gz
sub-23532_ses-1_task-rest_echo-2_bold.nii.gz
sub-23532_ses-1_task-rest_echo-3_bold.nii.gz
sub-23532_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23532_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23532_ses-1_task-TAU2_run-1_bold.nii
sub-23532_ses-1_task-TAU2_run-2_bold.nii
sub-23532_ses-1_task-rest_echo-1_bold.nii
sub-23532_ses-1_task-rest_echo-2_bold.nii
sub-23532_ses-1_task-rest_echo-3_bold.nii
29 NOT THERE

sub-23534_ses-1_task-rest_echo-1_bold.nii.gz
sub-23534_ses-1_task-rest_echo-2_bold.nii.gz
sub-23534_ses-1_task-rest_echo-3_bold.nii.gz
sub-23534_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23534_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23534_ses-1_task-TAU2_run-1_bold.nii
sub-23534_ses-1_task-TAU2_run-2_bold.nii
sub-23534_ses-1_task-rest_echo-1_bold.nii
sub-23534_ses-1_task-rest_echo-2_bold.nii
sub-23534_ses-1_task-rest_echo-3_bold.nii
30 NOT THERE

sub-23545_ses-1_task-rest_echo-1_bold.nii.gz
sub-23545_ses-1_task-rest_echo-2_bold.nii.gz
sub-23545_ses-1_task-rest_echo-3_bold.nii.gz
sub-23545_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23545_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23545_ses-1_task-TAU2_run-1_bold.nii
sub-23545_ses-1_task-TAU2_run-2_bold.nii
sub-23545_ses-1_task-rest_echo-1_bold.nii
sub-23545_ses-1_task-rest_echo-2_bold.nii
sub-23545_ses-1_task-rest_echo-3_bold.nii
31 NOT THERE

sub-23559_ses-1_task-rest_echo-1_bold.nii.gz
sub-23559_ses-1_task-rest_echo-2_bold.nii.gz
sub-23559_ses-1_task-rest_echo-3_bold.nii.gz
sub-23559_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23559_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23559_ses-1_task-TAU2_run-1_bold.nii
sub-23559_ses-1_task-TAU2_run-2_bold.nii
sub-23559_ses-1_task-rest_echo-1_bold.nii
sub-23559_ses-1_task-rest_echo-2_bold.nii
sub-23559_ses-1_task-rest_echo-3_bold.nii
32 NOT THERE

sub-23567_ses-1_task-rest_echo-1_bold.nii.gz
sub-23567_ses-1_task-rest_echo-2_bold.nii.gz
sub-23567_ses-1_task-rest_echo-3_bold.nii.gz
sub-23567_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23567_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23567_ses-1_task-TAU2_run-1_bold.nii
sub-23567_ses-1_task-TAU2_run-2_bold.nii
sub-23567_ses-1_task-rest_echo-1_bold.nii
sub-23567_ses-1_task-rest_echo-2_bold.nii
sub-23567_ses-1_task-rest_echo-3_bold.nii
33 NOT THERE

sub-23568_ses-1_task-rest_echo-1_bold.nii.gz
sub-23568_ses-1_task-rest_echo-2_bold.nii.gz
sub-23568_ses-1_task-rest_echo-3_bold.nii.gz
sub-23568_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23568_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23568_ses-1_task-TAU2_run-1_bold.nii
sub-23568_ses-1_task-TAU2_run-2_bold.nii
sub-23568_ses-1_task-rest_echo-1_bold.nii
sub-23568_ses-1_task-rest_echo-2_bold.nii
sub-23568_ses-1_task-rest_echo-3_bold.nii
34 NOT THERE

sub-23572_ses-1_task-rest_echo-1_bold.nii.gz
sub-23572_ses-1_task-rest_echo-2_bold.nii.gz
sub-23572_ses-1_task-rest_echo-3_bold.nii.gz
sub-23572_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23572_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23572_ses-1_task-TAU2_run-1_bold.nii
sub-23572_ses-1_task-TAU2_run-2_bold.nii
sub-23572_ses-1_task-rest_echo-1_bold.nii
sub-23572_ses-1_task-rest_echo-2_bold.nii
sub-23572_ses-1_task-rest_echo-3_bold.nii
35 NOT THERE

sub-23584_ses-1_task-rest_echo-1_bold.nii.gz
sub-23584_ses-1_task-rest_echo-2_bold.nii.gz
sub-23584_ses-1_task-rest_echo-3_bold.nii.gz
sub-23584_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23584_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23584_ses-1_task-TAU2_run-1_bold.nii
sub-23584_ses-1_task-TAU2_run-2_bold.nii
sub-23584_ses-1_task-rest_echo-1_bold.nii
sub-23584_ses-1_task-rest_echo-2_bold.nii
sub-23584_ses-1_task-rest_echo-3_bold.nii
36 NOT THERE

sub-23601_ses-1_task-rest_echo-1_bold.nii.gz
sub-23601_ses-1_task-rest_echo-2_bold.nii.gz
sub-23601_ses-1_task-rest_echo-3_bold.nii.gz
sub-23601_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23601_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23601_ses-1_task-TAU2_run-1_bold.nii
sub-23601_ses-1_task-TAU2_run-2_bold.nii
sub-23601_ses-1_task-rest_echo-1_bold.nii
sub-23601_ses-1_task-rest_echo-2_bold.nii
sub-23601_ses-1_task-rest_echo-3_bold.nii
37 NOT THERE

sub-23622_ses-1_task-rest_echo-1_bold.nii.gz
sub-23622_ses-1_task-rest_echo-2_bold.nii.gz
sub-23622_ses-1_task-rest_echo-3_bold.nii.gz
sub-23622_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23622_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23622_ses-1_task-TAU2_run-1_bold.nii
sub-23622_ses-1_task-TAU2_run-2_bold.nii
sub-23622_ses-1_task-rest_echo-1_bold.nii
sub-23622_ses-1_task-rest_echo-2_bold.nii
sub-23622_ses-1_task-rest_echo-3_bold.nii
38 NOT THERE

sub-23629_ses-1_task-rest_echo-1_bold.nii.gz
sub-23629_ses-1_task-rest_echo-2_bold.nii.gz
sub-23629_ses-1_task-rest_echo-3_bold.nii.gz
sub-23629_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23629_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23629_ses-1_task-TAU2_run-1_bold.nii
sub-23629_ses-1_task-TAU2_run-2_bold.nii
sub-23629_ses-1_task-rest_echo-1_bold.nii
sub-23629_ses-1_task-rest_echo-2_bold.nii
sub-23629_ses-1_task-rest_echo-3_bold.nii
39 NOT THERE

sub-23631_ses-1_task-rest_echo-1_bold.nii.gz
sub-23631_ses-1_task-rest_echo-2_bold.nii.gz
sub-23631_ses-1_task-rest_echo-3_bold.nii.gz
sub-23631_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23631_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23631_ses-1_task-TAU2_run-1_bold.nii
sub-23631_ses-1_task-TAU2_run-2_bold.nii
sub-23631_ses-1_task-rest_echo-1_bold.nii
sub-23631_ses-1_task-rest_echo-2_bold.nii
sub-23631_ses-1_task-rest_echo-3_bold.nii
40 NOT THERE

sub-23664_ses-1_task-rest_echo-1_bold.nii.gz
sub-23664_ses-1_task-rest_echo-2_bold.nii.gz
sub-23664_ses-1_task-rest_echo-3_bold.nii.gz
sub-23664_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23664_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23664_ses-1_task-TAU2_run-1_bold.nii
sub-23664_ses-1_task-TAU2_run-2_bold.nii
sub-23664_ses-1_task-rest_echo-1_bold.nii
sub-23664_ses-1_task-rest_echo-2_bold.nii
sub-23664_ses-1_task-rest_echo-3_bold.nii
41 NOT THERE

sub-23690_ses-1_task-rest_echo-1_bold.nii.gz
sub-23690_ses-1_task-rest_echo-2_bold.nii.gz
sub-23690_ses-1_task-rest_echo-3_bold.nii.gz
sub-23690_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23690_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23690_ses-1_task-TAU2_run-1_bold.nii
sub-23690_ses-1_task-TAU2_run-2_bold.nii
sub-23690_ses-1_task-rest_echo-1_bold.nii
sub-23690_ses-1_task-rest_echo-2_bold.nii
sub-23690_ses-1_task-rest_echo-3_bold.nii
42 NOT THERE

sub-23735_ses-1_task-rest_echo-1_bold.nii.gz
sub-23735_ses-1_task-rest_echo-2_bold.nii.gz
sub-23735_ses-1_task-rest_echo-3_bold.nii.gz
sub-23735_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23735_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23735_ses-1_task-TAU2_run-1_bold.nii
sub-23735_ses-1_task-TAU2_run-2_bold.nii
sub-23735_ses-1_task-rest_echo-1_bold.nii
sub-23735_ses-1_task-rest_echo-2_bold.nii
sub-23735_ses-1_task-rest_echo-3_bold.nii
43 NOT THERE

sub-23749_ses-1_task-rest_echo-1_bold.nii.gz
sub-23749_ses-1_task-rest_echo-2_bold.nii.gz
sub-23749_ses-1_task-rest_echo-3_bold.nii.gz
sub-23749_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23749_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23749_ses-1_task-TAU2_run-1_bold.nii
sub-23749_ses-1_task-TAU2_run-2_bold.nii
sub-23749_ses-1_task-rest_echo-1_bold.nii
sub-23749_ses-1_task-rest_echo-2_bold.nii
sub-23749_ses-1_task-rest_echo-3_bold.nii
44 NOT THERE

sub-23762_ses-1_task-rest_echo-1_bold.nii.gz
sub-23762_ses-1_task-rest_echo-2_bold.nii.gz
sub-23762_ses-1_task-rest_echo-3_bold.nii.gz
sub-23762_ses-1_task-TAU2_run-1_bold.nii.gz
sub-23762_ses-1_task-TAU2_run-2_bold.nii.gz
sub-23762_ses-1_task-TAU2_run-1_bold.nii
sub-23762_ses-1_task-TAU2_run-2_bold.nii
sub-23762_ses-1_task-rest_echo-1_bold.nii
sub-23762_ses-1_task-rest_echo-2_bold.nii

In [7]:
base

'..\\Pediatric_Anxiety_Disorder'

In [14]:
# Configuration
subject_list = [23381, 23382, 23386, 23392, 23407, 23432, 23442, 23480, 23483, 23485, 23494, 23501, 23524, 23532, 23534, 23545, 23559, 23567, 23568, 23572, 23584, 23601, 23622, 23629, 23631, 23664, 23690, 23735, 23749, 23762, 23779, 23822, 23842, 23855, 23865, 23871, 23878, 23883, 23892, 23910, 23923, 23925, 23946, 23971, 23972, 23979, 23985, 23986, 23987, 23991, 23996, 24004, 24015, 24017, 24021, 24022, 24029, 24033, 24038, 24039, 24040, 24046, 24050, 24067, 24073, 24089, 24091, 24106, 24115, 24118, 24127, 24139, 24142, 24145, 24146, 24148, 24151, 24182, 24197, 24198, 24212, 24217, 24236, 24240, 24260, 24270, 24275, 24276, 24300, 24353]
dest_dir = os.path.join('..','C2AnatScans')

# Create destination if it doesn't exist
os.makedirs(dest_dir, exist_ok=True)

for sub in subject_list:
    # Construct the path to the anat folder
    anat_path = os.path.join(base, 'sub-'+str(sub), 'ses-1', 'anat')
    
    # Use glob to find all .nii files in that folder
    nii_files = glob.glob(os.path.join(anat_path, "*.nii"))
    print(nii_files)
    
    for file_path in nii_files:
        # Define new filename to avoid overwriting (e.g., sub-23381_anat.nii)
        filename = os.path.basename(file_path)
        destination = os.path.join(dest_dir, filename)
        
        # Copy the file
        shutil.copy2(file_path, destination)
        print(f"Copied: {filename}")

['..\\Pediatric_Anxiety_Disorder\\sub-23381\\ses-1\\anat\\sub-23381_ses-1_T1w.nii']
Copied: sub-23381_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23382\\ses-1\\anat\\sub-23382_ses-1_T1w.nii']
Copied: sub-23382_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23386\\ses-1\\anat\\sub-23386_ses-1_T1w.nii']
Copied: sub-23386_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23392\\ses-1\\anat\\sub-23392_ses-1_T1w.nii']
Copied: sub-23392_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23407\\ses-1\\anat\\sub-23407_ses-1_T1w.nii']
Copied: sub-23407_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23432\\ses-1\\anat\\sub-23432_ses-1_T1w.nii']
Copied: sub-23432_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23442\\ses-1\\anat\\sub-23442_ses-1_T1w.nii']
Copied: sub-23442_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23480\\ses-1\\anat\\sub-23480_ses-1_T1w.nii']
Copied: sub-23480_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23483\\ses-1\\anat\\sub-23483_ses-1_T1w.nii']
Copied: sub-23483_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23485\\ses-1\\anat\\sub-23485_ses-1_T1w.nii']
Copied: sub-23485_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23494\\ses-1\\anat\\sub-23494_ses-1_T1w.nii']
Copied: sub-23494_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23501\\ses-1\\anat\\sub-23501_ses-1_T1w.nii']
Copied: sub-23501_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23524\\ses-1\\anat\\sub-23524_ses-1_T1w.nii']
Copied: sub-23524_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23532\\ses-1\\anat\\sub-23532_ses-1_T1w.nii']
Copied: sub-23532_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23534\\ses-1\\anat\\sub-23534_ses-1_T1w.nii']
Copied: sub-23534_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23545\\ses-1\\anat\\sub-23545_ses-1_T1w.nii']
Copied: sub-23545_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23559\\ses-1\\anat\\sub-23559_ses-1_T1w.nii']
Copied: sub-23559_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23567\\ses-1\\anat\\sub-23567_ses-1_T1w.nii']
Copied: sub-23567_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23568\\ses-1\\anat\\sub-23568_ses-1_T1w.nii']
Copied: sub-23568_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23572\\ses-1\\anat\\sub-23572_ses-1_T1w.nii']
Copied: sub-23572_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23584\\ses-1\\anat\\sub-23584_ses-1_T1w.nii']
Copied: sub-23584_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23601\\ses-1\\anat\\sub-23601_ses-1_T1w.nii']
Copied: sub-23601_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23622\\ses-1\\anat\\sub-23622_ses-1_T1w.nii']
Copied: sub-23622_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23629\\ses-1\\anat\\sub-23629_ses-1_T1w.nii']
Copied: sub-23629_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23631\\ses-1\\anat\\sub-23631_ses-1_T1w.nii']
Copied: sub-23631_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23664\\ses-1\\anat\\sub-23664_ses-1_T1w.nii']
Copied: sub-23664_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23690\\ses-1\\anat\\sub-23690_ses-1_T1w.nii']
Copied: sub-23690_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23735\\ses-1\\anat\\sub-23735_ses-1_T1w.nii']
Copied: sub-23735_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23749\\ses-1\\anat\\sub-23749_ses-1_T1w.nii']
Copied: sub-23749_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23762\\ses-1\\anat\\sub-23762_ses-1_T1w.nii']
Copied: sub-23762_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23779\\ses-1\\anat\\sub-23779_ses-1_T1w.nii']
Copied: sub-23779_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23822\\ses-1\\anat\\sub-23822_ses-1_T1w.nii']
Copied: sub-23822_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23842\\ses-1\\anat\\sub-23842_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-23842\\ses-1\\anat\\msub-23842_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-23842\\ses-1\\anat\\c1sub-23842_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-23842\\ses-1\\anat\\c2sub-23842_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-23842\\ses-1\\anat\\c3sub-23842_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-23842\\ses-1\\anat\\c4sub-23842_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-23842\\ses-1\\anat\\c5sub-23842_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-23842\\ses-1\\anat\\y_sub-23842_ses-1_T1w.nii']
Copied: sub-23842_ses-1_T1w.nii
Copied: msub-23842_ses-1_T1w.nii
Copied: c1sub-23842_ses-1_T1w.nii
Copied: c2sub-23842_ses-1_T1w.nii
Copied: c3sub-23842_ses-1_T1w.nii
Copied: c4sub-23842_ses-1_T1w.nii
Copied: c5sub-23842_ses-1_T1w.nii
Copied: y_sub-23842_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23855\\ses-1\\anat\\sub-23855_ses-1_T1w.nii']
Copied: sub-23855_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23865\\ses-1\\anat\\sub-23865_ses-1_T1w.nii']
Copied: sub-23865_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23871\\ses-1\\anat\\sub-23871_ses-1_T1w.nii']
Copied: sub-23871_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23878\\ses-1\\anat\\sub-23878_ses-1_T1w.nii']
Copied: sub-23878_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23883\\ses-1\\anat\\sub-23883_ses-1_T1w.nii']
Copied: sub-23883_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23892\\ses-1\\anat\\sub-23892_ses-1_T1w.nii']
Copied: sub-23892_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23910\\ses-1\\anat\\sub-23910_ses-1_T1w.nii']
Copied: sub-23910_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23923\\ses-1\\anat\\sub-23923_ses-1_T1w.nii']
Copied: sub-23923_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23925\\ses-1\\anat\\sub-23925_ses-1_T1w.nii']
Copied: sub-23925_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23946\\ses-1\\anat\\sub-23946_ses-1_T1w.nii']
Copied: sub-23946_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23971\\ses-1\\anat\\sub-23971_ses-1_T1w.nii']
Copied: sub-23971_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23972\\ses-1\\anat\\sub-23972_ses-1_T1w.nii']
Copied: sub-23972_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23979\\ses-1\\anat\\sub-23979_ses-1_T1w.nii']
Copied: sub-23979_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23985\\ses-1\\anat\\sub-23985_ses-1_T1w.nii']
Copied: sub-23985_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23986\\ses-1\\anat\\sub-23986_ses-1_T1w.nii']
Copied: sub-23986_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23987\\ses-1\\anat\\sub-23987_ses-1_T1w.nii']
Copied: sub-23987_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23991\\ses-1\\anat\\sub-23991_ses-1_T1w.nii']
Copied: sub-23991_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23996\\ses-1\\anat\\sub-23996_ses-1_T1w.nii']
Copied: sub-23996_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24004\\ses-1\\anat\\sub-24004_ses-1_T1w.nii']
Copied: sub-24004_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24015\\ses-1\\anat\\sub-24015_ses-1_T1w.nii']
Copied: sub-24015_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24017\\ses-1\\anat\\sub-24017_ses-1_T1w.nii']
Copied: sub-24017_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24021\\ses-1\\anat\\sub-24021_ses-1_T1w.nii']
Copied: sub-24021_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24022\\ses-1\\anat\\sub-24022_ses-1_T1w.nii']
Copied: sub-24022_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24029\\ses-1\\anat\\sub-24029_ses-1_T1w.nii']
Copied: sub-24029_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24033\\ses-1\\anat\\sub-24033_ses-1_T1w.nii']
Copied: sub-24033_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24038\\ses-1\\anat\\sub-24038_ses-1_T1w.nii']
Copied: sub-24038_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24039\\ses-1\\anat\\sub-24039_ses-1_T1w.nii']
Copied: sub-24039_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24040\\ses-1\\anat\\sub-24040_ses-1_T1w.nii']
Copied: sub-24040_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24046\\ses-1\\anat\\sub-24046_ses-1_T1w.nii']
Copied: sub-24046_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24050\\ses-1\\anat\\sub-24050_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-24050\\ses-1\\anat\\msub-24050_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-24050\\ses-1\\anat\\c1sub-24050_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-24050\\ses-1\\anat\\c2sub-24050_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-24050\\ses-1\\anat\\c3sub-24050_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-24050\\ses-1\\anat\\c4sub-24050_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-24050\\ses-1\\anat\\c5sub-24050_ses-1_T1w.nii', '..\\Pediatric_Anxiety_Disorder\\sub-24050\\ses-1\\anat\\y_sub-24050_ses-1_T1w.nii']
Copied: sub-24050_ses-1_T1w.nii
Copied: msub-24050_ses-1_T1w.nii
Copied: c1sub-24050_ses-1_T1w.nii
Copied: c2sub-24050_ses-1_T1w.nii
Copied: c3sub-24050_ses-1_T1w.nii
Copied: c4sub-24050_ses-1_T1w.nii
Copied: c5sub-24050_ses-1_T1w.nii
Copied: y_sub-24050_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24067\\ses-1\\anat\\sub-24067_ses-1_T1w.nii']
Copied: sub-24067_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24073\\ses-1\\anat\\sub-24073_ses-1_T1w.nii']
Copied: sub-24073_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24089\\ses-1\\anat\\sub-24089_ses-1_T1w.nii']
Copied: sub-24089_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24091\\ses-1\\anat\\sub-24091_ses-1_T1w.nii']
Copied: sub-24091_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24106\\ses-1\\anat\\sub-24106_ses-1_T1w.nii']
Copied: sub-24106_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24115\\ses-1\\anat\\sub-24115_ses-1_T1w.nii']
Copied: sub-24115_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24118\\ses-1\\anat\\sub-24118_ses-1_T1w.nii']
Copied: sub-24118_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24127\\ses-1\\anat\\sub-24127_ses-1_T1w.nii']
Copied: sub-24127_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24139\\ses-1\\anat\\sub-24139_ses-1_T1w.nii']
Copied: sub-24139_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24142\\ses-1\\anat\\sub-24142_ses-1_T1w.nii']
Copied: sub-24142_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24145\\ses-1\\anat\\sub-24145_ses-1_T1w.nii']
Copied: sub-24145_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24146\\ses-1\\anat\\sub-24146_ses-1_T1w.nii']
Copied: sub-24146_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24148\\ses-1\\anat\\sub-24148_ses-1_T1w.nii']
Copied: sub-24148_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24151\\ses-1\\anat\\sub-24151_ses-1_T1w.nii']
Copied: sub-24151_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24182\\ses-1\\anat\\sub-24182_ses-1_T1w.nii']
Copied: sub-24182_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24197\\ses-1\\anat\\sub-24197_ses-1_T1w.nii']
Copied: sub-24197_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24198\\ses-1\\anat\\sub-24198_ses-1_T1w.nii']
Copied: sub-24198_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24212\\ses-1\\anat\\sub-24212_ses-1_T1w.nii']
Copied: sub-24212_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24217\\ses-1\\anat\\sub-24217_ses-1_T1w.nii']
Copied: sub-24217_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24236\\ses-1\\anat\\sub-24236_ses-1_T1w.nii']
Copied: sub-24236_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24240\\ses-1\\anat\\sub-24240_ses-1_T1w.nii']
Copied: sub-24240_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24260\\ses-1\\anat\\sub-24260_ses-1_T1w.nii']
Copied: sub-24260_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24270\\ses-1\\anat\\sub-24270_ses-1_T1w.nii']
Copied: sub-24270_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24275\\ses-1\\anat\\sub-24275_ses-1_T1w.nii']
Copied: sub-24275_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24276\\ses-1\\anat\\sub-24276_ses-1_T1w.nii']
Copied: sub-24276_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24300\\ses-1\\anat\\sub-24300_ses-1_T1w.nii']
Copied: sub-24300_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-24353\\ses-1\\anat\\sub-24353_ses-1_T1w.nii']
Copied: sub-24353_ses-1_T1w.nii

In [15]:
# Configuration
subject_list = [21100, 22734, 22829, 22831, 22847, 22860, 22862, 22873, 22906, 22956, 23010, 23014, 23028, 23044]
dest_dir = os.path.join('..','C1AnatScans')

# Create destination if it doesn't exist
os.makedirs(dest_dir, exist_ok=True)

for sub in subject_list:
    # Construct the path to the anat folder
    anat_path = os.path.join(base, 'sub-'+str(sub), 'ses-1', 'anat')
    
    # Use glob to find all .nii files in that folder
    nii_files = glob.glob(os.path.join(anat_path, "*.nii"))
    print(nii_files)
    
    for file_path in nii_files:
        # Define new filename to avoid overwriting (e.g., sub-23381_anat.nii)
        filename = os.path.basename(file_path)
        destination = os.path.join(dest_dir, filename)
        
        # Copy the file
        shutil.copy2(file_path, destination)
        print(f"Copied: {filename}")

[]
['..\\Pediatric_Anxiety_Disorder\\sub-22734\\ses-1\\anat\\sub-22734_ses-1_T1w.nii']
Copied: sub-22734_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-22829\\ses-1\\anat\\sub-22829_ses-1_T1w.nii']
Copied: sub-22829_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-22831\\ses-1\\anat\\sub-22831_ses-1_T1w.nii']
Copied: sub-22831_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-22847\\ses-1\\anat\\sub-22847_ses-1_T1w.nii']
Copied: sub-22847_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-22860\\ses-1\\anat\\sub-22860_ses-1_T1w.nii']
Copied: sub-22860_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-22862\\ses-1\\anat\\sub-22862_ses-1_T1w.nii']
Copied: sub-22862_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-22873\\ses-1\\anat\\sub-22873_ses-1_T1w.nii']
Copied: sub-22873_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-22906\\ses-1\\anat\\sub-22906_ses-1_T1w.nii']
Copied: sub-22906_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-22956\\ses-1\\anat\\sub-22956_ses-1_T1w.nii']
Copied: sub-22956_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23010\\ses-1\\anat\\sub-23010_ses-1_T1w.nii']
Copied: sub-23010_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23014\\ses-1\\anat\\sub-23014_ses-1_T1w.nii']
Copied: sub-23014_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23028\\ses-1\\anat\\sub-23028_ses-1_T1w.nii']
Copied: sub-23028_ses-1_T1w.nii
['..\\Pediatric_Anxiety_Disorder\\sub-23044\\ses-1\\anat\\sub-23044_ses-1_T1w.nii']
Copied: sub-23044_ses-1_T1w.nii

In [26]:
print([int(os.path.basename(f)[4:9]) for f in glob.glob(os.path.join('..', 'C1AnatScans', "*.nii"))])

[22734, 22829, 22831, 22847, 22860, 22862, 22873, 22906, 22956, 23010, 23014, 23028, 23044]

In [6]:
shutil.copy?

Signature: shutil.copy(src, dst, *, follow_symlinks=True)
Docstring:
Copy data and mode bits ("cp src dst"). Return the file's destination.

The destination may be a directory.

If follow_symlinks is false, symlinks won't be followed. This
resembles GNU's "cp -P src dst".

If source and destination are the same file, a SameFileError will be
raised.
File:      c:\users\aleen\appdata\local\programs\python\python312\lib\shutil.py
Type:      function

In [20]:
c1 = [20131, 20209, 20725, 21100, 21214, 21508, 22268, 22281, 22286, 22295, 22346, 22353, 22354, 22365, 22366, 22380, 22381, 22475, 22477, 22482, 22487, 22494, 22532, 22536, 22587, 22600, 22623, 22630, 22686, 22687, 22727, 22734, 22829, 22831, 22847, 22860, 22862, 22873, 22906, 22956, 23010, 23014, 23028, 23044]
c1_prep_done = []
for c in c1:
    for f in glob.glob(os.path.join(base, 'sub-'+str(c), 'ses-1', 'anat', 'y_sub*')):
        c1_prep_done.append(int(os.path.basename(f)[6:11]))
print(c1_prep_done)
print(len(c1_prep_done))

[20131, 20209, 20725, 21100, 21214, 21508, 22268, 22281, 22286, 22295, 22346, 22353, 22354, 22365, 22366, 22380, 22381, 22475, 22477, 22482, 22487, 22494, 22532, 22536, 22587, 22600, 22623, 22630, 22686, 22687, 22727, 22734, 22829, 22831, 22847, 22860, 22862, 22873, 22906, 22956, 23010, 23014, 23028, 23044]
44

In [21]:
print([c for c in c1 if c not in c1_prep_done])

[]

In [22]:
c2 = [22172, 22818, 22871, 23072, 23123, 23257, 23261, 23294, 23303, 23314, 23317, 23342, 23353, 23362, 23376, 23381, 23382, 23386, 23392, 23407, 23432, 23442, 23480, 23483, 23485, 23494, 23501, 23524, 23532, 23534, 23545, 23559, 23567, 23568, 23572, 23584, 23601, 23622, 23629, 23631, 23664, 23690, 23735, 23749, 23762, 23779, 23822, 23842, 23855, 23865, 23871, 23878, 23883, 23892, 23910, 23923, 23925, 23946, 23971, 23972, 23979, 23985, 23986, 23987, 23991, 23996, 24004, 24015, 24017, 24021, 24022, 24029, 24033, 24038, 24039, 24040, 24046, 24050, 24067, 24073, 24089, 24091, 24106, 24115, 24118, 24127, 24139, 24142, 24145, 24146, 24148, 24151, 24182, 24197, 24198, 24212, 24217, 24236, 24240, 24260, 24270, 24275, 24276, 24300, 24353]
c2_prep_done = []
for c in c2:
    for f in glob.glob(os.path.join(base, 'sub-'+str(c), 'ses-1', 'anat', 'y_sub*')):
        c2_prep_done.append(int(os.path.basename(f)[6:11]))
print(c2_prep_done)
print(len(c2_prep_done))

[22172, 22818, 22871, 23072, 23123, 23257, 23261, 23294, 23303, 23314, 23317, 23342, 23353, 23362, 23376, 23381, 23382, 23386, 23392, 23407, 23432, 23442, 23480, 23483, 23485, 23494, 23501, 23524, 23532, 23534, 23545, 23559, 23567, 23568, 23572, 23584, 23601, 23622, 23629, 23631, 23664, 23690, 23735, 23749, 23762, 23779, 23822, 23842, 23855, 23865, 23871, 23878, 23883, 23892, 23910, 23923, 23925, 23946, 23971, 23972, 23979, 23985, 23986, 23987, 23991, 23996, 24004, 24015, 24017, 24021, 24022, 24029, 24033, 24038, 24039, 24040, 24046, 24050, 24067, 24073, 24089, 24091, 24106, 24115, 24118, 24127, 24139, 24142, 24145, 24146, 24148, 24151, 24182, 24197, 24198, 24212, 24217, 24236, 24240, 24260, 24270, 24275, 24276, 24300, 24353]
105

In [23]:
print([c for c in c2 if c not in c2_prep_done])

[]

In [7]:
(60/149)*100

40.26845637583892

In [8]:
pheno = pd.read_csv(os.path.join(base,'phenotype','phenotype.tsv'), delimiter='\t')
pheno

,participant_id,sex,age_baseline,KSADS_MAIN_DIAGNOSIS,WASI_FULL_2_IQ,INCOME,RACE_WHITE,RACE_BLACK,RACE_ASIAN,RACE_MULTIPLE,...,DOT_PROBE_BASELINE_BIAS,DOT_PROBE_BASELINE_ABV,DOT_PROBE_BASELINE_DDM_DRIFT_RATE,DOT_PROBE_BASELINE_DDM_BIAS,DOT_PROBE_T2_ACCURACY,DOT_PROBE_T2_MEDIAN_RT_CONGRUENT,DOT_PROBE_T2_MEDIAN_RT_INCONGRUENT,DOT_PROBE_T2_MEDIAN_RT_NEUTRAL,DOT_PROBE_T2_BIAS,DOT_PROBE_T2_ABV
0,sub-020131,1,17,HV,122.0,8.0,1,-1,-1,-1,...,-26.62,0.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,sub-020209,1,16,HV,118.0,8.0,1,-1,-1,-1,...,-5.21,0.07,5.04,0.01,NaN,NaN,NaN,NaN,NaN,NaN
2,sub-020725,1,14,HV,116.0,8.0,1,-1,-1,-1,...,-21.97,0.07,6.57,-0.04,NaN,NaN,NaN,NaN,NaN,NaN
3,sub-021100,-1,11,HV,134.0,8.0,1,-1,-1,-1,...,16.49,0.10,3.71,0.02,NaN,NaN,NaN,NaN,NaN,NaN
4,sub-021214,1,11,HV,130.0,9.0,1,-1,-1,-1,...,4.83,0.06,5.28,-0.01,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,sub-024270,-1,13,HV,NaN,8.0,-1,-1,-1,1,...,-0.80,0.04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,sub-024275,-1,15,HV,114.0,9.0,1,-1,-1,-1,...,18.53,0.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,sub-024276,1,9,HV,136.0,8.0,-1,-1,-1,1,...,15.08,0.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,sub-024300,-1,9,ANX,117.0,8.0,-1,-1,-1,1,...,-16.38,0.06,NaN,NaN,0.98,512.5,500.0,523.0,-7.55,0.06
148,sub-024353,-1,10,ANX,111.0,8.0,1,-1,-1,-1,...,-26.00,0.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
c1_anxiety = []
c1_healthy = []
for c in c1_prep_done:
    if pheno[pheno['participant_id']=='sub-0'+str(c)]['KSADS_MAIN_DIAGNOSIS'].values[0]=='ANX':
        c1_anxiety.append(c)
    else:
        c1_healthy.append(c)

In [25]:
print(c1_anxiety)
print(len(c1_anxiety))

[22286, 22295, 22475, 22477, 22482, 22487, 22532, 22600, 22630, 22727, 22829, 22831, 22847, 22860, 22873, 22906, 22956, 23014]
18

In [26]:
print(c1_healthy)
print(len(c1_healthy))

[20131, 20209, 20725, 21100, 21214, 21508, 22268, 22281, 22346, 22353, 22354, 22365, 22366, 22380, 22381, 22494, 22536, 22587, 22623, 22686, 22687, 22734, 22862, 23010, 23028, 23044]
26

In [27]:
c2_anxiety = []
c2_healthy = []
for c in c2_prep_done:
    if pheno[pheno['participant_id']=='sub-0'+str(c)]['KSADS_MAIN_DIAGNOSIS'].values[0]=='ANX':
        c2_anxiety.append(c)
    else:
        c2_healthy.append(c)

In [28]:
print(c2_anxiety)
print(len(c2_anxiety))

[22818, 23362, 23376, 23381, 23382, 23386, 23392, 23407, 23442, 23480, 23483, 23485, 23494, 23501, 23532, 23572, 23584, 23601, 23622, 23629, 23631, 23664, 23690, 23735, 23749, 23762, 23779, 23822, 23842, 23855, 23871, 23883, 23910, 23923, 23925, 23946, 23971, 23972, 23985, 23987, 24015, 24017, 24029, 24039, 24040, 24046, 24067, 24089, 24091, 24106, 24115, 24118, 24139, 24146, 24148, 24151, 24182, 24217, 24236, 24240, 24260, 24300, 24353]
63

In [29]:
print(c2_healthy)
print(len(c2_healthy))

[22172, 22871, 23072, 23123, 23257, 23261, 23294, 23303, 23314, 23317, 23342, 23353, 23432, 23524, 23534, 23545, 23559, 23567, 23568, 23865, 23878, 23892, 23979, 23986, 23991, 23996, 24004, 24021, 24022, 24033, 24038, 24050, 24073, 24127, 24142, 24145, 24197, 24198, 24212, 24270, 24275, 24276]
42

In [30]:
c1_rem_anx = []
c1_rem_hlth = []
for c in [c for c in c1 if c not in c1_prep_done]:
    if pheno[pheno['participant_id']=='sub-0'+str(c)]['KSADS_MAIN_DIAGNOSIS'].values[0]=='ANX':
        c1_rem_anx.append(c)
    else:
        c1_rem_hlth.append(c)
print(c1_rem_anx)
print(c1_rem_hlth)

[]
[]

In [31]:
c2_rem_anx = []
c2_rem_hlth = []
for c in [c for c in c2 if c not in c2_prep_done]:
    if pheno[pheno['participant_id']=='sub-0'+str(c)]['KSADS_MAIN_DIAGNOSIS'].values[0]=='ANX':
        c2_rem_anx.append(c)
    else:
        c2_rem_hlth.append(c)
print(c2_rem_anx)
print(c2_rem_hlth)

[]
[]

In [32]:
len([c for c in c2 if c not in c2_prep_done])

0

In [19]:
56/89

0.6292134831460674

In [20]:
33/89

0.3707865168539326

In [21]:
48-5

43

In [35]:
27+5

32

In [38]:
43+8

51

In [39]:
32+6

38

In [57]:
pheno.columns

Index(['participant_id', 'sex', 'age_baseline', 'KSADS_MAIN_DIAGNOSIS',
       'WASI_FULL_2_IQ', 'INCOME', 'RACE_WHITE', 'RACE_BLACK', 'RACE_ASIAN',
       'RACE_MULTIPLE', 'ETHNICITY', 'CGAS_BASELINE_SCORE', 'COHORT',
       'SCANNER', 'SCARED_BASELINE_YOUTH_RATING',
       'SCARED_BASELINE_PARENT_RATING', 'PARS_BASELINE_CLINICIAN_RATING',
       'PARS_MID-TREATMENT_CLINICIAN_RATING',
       'PARS_POST-TREATMENT_CLINICIAN_RATING', 'ABMT',
       'NEURAL_EFFICIENCY_BASELINE_FULL_CORRELATIONS',
       'NEURAL_EFFICIENCY_BASELINE_PARTIAL_CORRELATIONS', 'DAYS_BTW_SCANS',
       'NEURAL_EFFICIENCY_T2_FULL_CORRELATIONS',
       'NEURAL_EFFICIENCY_T2_PARTIAL_CORRELATIONS',
       'DOT_PROBE_BASELINE_ACCURACY', 'DOT_PROBE_BASELINE_MEDIAN_RT_CONGRUENT',
       'DOT_PROBE_BASELINE_MEDIAN_RT_INCONGRUENT',
       'DOT_PROBE_BASELINE_MEDIAN_RT_NEUTRAL', 'DOT_PROBE_BASELINE_BIAS',
       'DOT_PROBE_BASELINE_ABV', 'DOT_PROBE_BASELINE_DDM_DRIFT_RATE',
       'DOT_PROBE_BASELINE_DDM_BIAS', 'DOT_PROBE_T2_ACCURACY',
       'DOT_PROBE_T2_MEDIAN_RT_CONGRUENT',
       'DOT_PROBE_T2_MEDIAN_RT_INCONGRUENT', 'DOT_PROBE_T2_MEDIAN_RT_NEUTRAL',
       'DOT_PROBE_T2_BIAS', 'DOT_PROBE_T2_ABV'],
      dtype='object')

In [65]:
pheno['ETHNICITY'].unique()

array([-1,  1], dtype=int64)

In [71]:
pheno[pheno.isnull()].value_counts()

Series([], Name: count, dtype: int64)

In [23]:
-np.log10(0.05)

1.3010299956639813

In [38]:
np.arctanh(-0.996)

-3.106303047875759

In [40]:
40/100 * 149

59.6

In [41]:
149-60

89

In [42]:
80/100 * 89

71.2

In [43]:
89-72

17

In [48]:
(40*40 - 40)/2

780.0

In [49]:
"hello".upper()

'HELLO'

In [33]:
len([24046, 24067, 24089, 24091, 24106, 24115, 24118, 24139, 24146, 24148, 24151, 24182, 24217, 24236, 24240, 24260, 24300, 24353])

18

In [5]:
ROOT_FOLDER = os.path.join('..', 'dataset_holdouts', '10_holdouts')
CSV_FILENAME = 'ML_Dataset_holdout-*.csv'

In [6]:
OLD_COL_NAME = 'subject_id'
NEW_COL_NAME = 'participant_id'

In [7]:
def modify_value(val):
    return 'sub-0'+str(val)

In [8]:
def modify_csv(filepath):
    df = pd.read_csv(filepath)
    if OLD_COL_NAME not in df.columns:
        print(f"[SKIP] Column '{OLD_COL_NAME}' not found in: {filepath}")
        return

    df.rename(columns={OLD_COL_NAME: NEW_COL_NAME}, inplace=True)
    df[NEW_COL_NAME] = df[NEW_COL_NAME].apply(modify_value)
    df.to_csv(filepath, index=False)
    print(f"[OK] Processed: {filepath}")

In [9]:
pattern = os.path.join(ROOT_FOLDER, '**', CSV_FILENAME)
csv_files = glob.glob(pattern, recursive=True)
csv_files

['..\\dataset_holdouts\\10_holdouts\\holdout-01\\uncorrected_alpha-0.05_two-sided\\ML_Dataset_holdout-01.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-01\\uncorrected_alpha-0.01_two-sided\\ML_Dataset_holdout-01.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-01\\fdr-corrected_alpha-0.05_two-sided\\ML_Dataset_holdout-01.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-01\\uncorrected_alpha-0.01_two-sided_cluster-thresh-20\\ML_Dataset_holdout-01.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-02\\uncorrected_alpha-0.05_two-sided\\ML_Dataset_holdout-02.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-02\\uncorrected_alpha-0.01_two-sided\\ML_Dataset_holdout-02.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-03\\uncorrected_alpha-0.05_two-sided\\ML_Dataset_holdout-03.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-03\\uncorrected_alpha-0.01_two-sided\\ML_Dataset_holdout-03.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-04\\uncorrected_alpha-0.05_two-sided\\ML_Dataset_holdout-04.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-04\\uncorrected_alpha-0.01_two-sided\\ML_Dataset_holdout-04.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-04\\uncorrected_alpha-0.01_two-sided_cluster-thresh-20\\ML_Dataset_holdout-04.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-05\\uncorrected_alpha-0.05_two-sided\\ML_Dataset_holdout-05.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-05\\uncorrected_alpha-0.01_two-sided\\ML_Dataset_holdout-05.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-05\\uncorrected_alpha-0.01_two-sided_cluster-thresh-20\\ML_Dataset_holdout-05.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-06\\uncorrected_alpha-0.05_two-sided\\ML_Dataset_holdout-06.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-06\\uncorrected_alpha-0.01_two-sided\\ML_Dataset_holdout-06.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-07\\uncorrected_alpha-0.05_two-sided\\ML_Dataset_holdout-07.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-07\\uncorrected_alpha-0.01_two-sided\\ML_Dataset_holdout-07.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-08\\uncorrected_alpha-0.05_two-sided\\ML_Dataset_holdout-08.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-08\\uncorrected_alpha-0.01_two-sided\\ML_Dataset_holdout-08.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-09\\uncorrected_alpha-0.05_two-sided\\ML_Dataset_holdout-09.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-09\\uncorrected_alpha-0.01_two-sided\\ML_Dataset_holdout-09.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-10\\uncorrected_alpha-0.05_two-sided\\ML_Dataset_holdout-10.csv',
 '..\\dataset_holdouts\\10_holdouts\\holdout-10\\uncorrected_alpha-0.01_two-sided\\ML_Dataset_holdout-10.csv']

In [10]:
print(f"Found {len(csv_files)} CSV file(s). Processing...\n")
for filepath in csv_files:
    modify_csv(filepath)
print("\nDone!")

Found 24 CSV file(s). Processing...

[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-01\uncorrected_alpha-0.05_two-sided\ML_Dataset_holdout-01.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-01\uncorrected_alpha-0.01_two-sided\ML_Dataset_holdout-01.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-01\fdr-corrected_alpha-0.05_two-sided\ML_Dataset_holdout-01.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-01\uncorrected_alpha-0.01_two-sided_cluster-thresh-20\ML_Dataset_holdout-01.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-02\uncorrected_alpha-0.05_two-sided\ML_Dataset_holdout-02.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-02\uncorrected_alpha-0.01_two-sided\ML_Dataset_holdout-02.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-03\uncorrected_alpha-0.05_two-sided\ML_Dataset_holdout-03.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-03\uncorrected_alpha-0.01_two-sided\ML_Dataset_holdout-03.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-04\uncorrected_alpha-0.05_two-sided\ML_Dataset_holdout-04.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-04\uncorrected_alpha-0.01_two-sided\ML_Dataset_holdout-04.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-04\uncorrected_alpha-0.01_two-sided_cluster-thresh-20\ML_Dataset_holdout-04.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-05\uncorrected_alpha-0.05_two-sided\ML_Dataset_holdout-05.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-05\uncorrected_alpha-0.01_two-sided\ML_Dataset_holdout-05.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-05\uncorrected_alpha-0.01_two-sided_cluster-thresh-20\ML_Dataset_holdout-05.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-06\uncorrected_alpha-0.05_two-sided\ML_Dataset_holdout-06.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-06\uncorrected_alpha-0.01_two-sided\ML_Dataset_holdout-06.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-07\uncorrected_alpha-0.05_two-sided\ML_Dataset_holdout-07.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-07\uncorrected_alpha-0.01_two-sided\ML_Dataset_holdout-07.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-08\uncorrected_alpha-0.05_two-sided\ML_Dataset_holdout-08.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-08\uncorrected_alpha-0.01_two-sided\ML_Dataset_holdout-08.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-09\uncorrected_alpha-0.05_two-sided\ML_Dataset_holdout-09.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-09\uncorrected_alpha-0.01_two-sided\ML_Dataset_holdout-09.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-10\uncorrected_alpha-0.05_two-sided\ML_Dataset_holdout-10.csv
[OK] Processed: ..\dataset_holdouts\10_holdouts\holdout-10\uncorrected_alpha-0.01_two-sided\ML_Dataset_holdout-10.csv

Done!